window.WEEK4_DATA = {
  "copy": {
    "zh-CN": {
      "eyebrow": "Week 4 · Grok 网页实操",
      "title": "先让 AI 问清楚<br>再让它写 Prompt",
      "lead": "从一句“帮我写个 SOP”开始，通过回答、修正和确认，把需求整理成可在新对话执行的 prompt。",
      "goal": "学习目标",
      "goalText": "使用 Prompt 教练 skill 整理需求，生成自己的 prompt，并在新对话中检查结果。",
      "start": "开始练习",
      "downloadPack": "下载学员材料包",
      "nav1": "从需求到 Prompt",
      "nav2": "选一个有依据的 SOP",
      "nav3": "在 Grok 接入 skill",
      "nav4": "问答、修正与确认",
      "nav5": "使用新对话验证",
      "nav6": "根据结果修改",
      "nav7": "换成自己的工作",
      "nav8": "学习材料",
      "s1": "1. 先说你要做什么",
      "s1Intro": "Week 3 介绍了角色、背景、任务、格式和示例。让 AI 帮你问清这些信息，再检查它是否正确理解需求。",
      "s1Quote": "不用一开始就写得专业。先把工作里的麻烦说出来，再把 AI 理解偏的地方改回来。",
      "route1": "说需求",
      "route2": "AI 追问",
      "route3": "复述、修正",
      "route4": "用户确认",
      "route5": "生成 Prompt",
      "route6": "新对话验证",
      "route7": "按结果修改",
      "s1Note": "skill（保存好的问答流程）让 AI 按步骤帮你整理需求。检查它是否问到关键缺口、保留需求修正，并让新对话仍能读到完整要求。",
      "s2": "2. 选一个能对照的流程",
      "s2Intro": "这次要写的是“客户投诉接收与交接”。例如，客户把投诉发到客服邮箱，新人需要知道先登记什么、交给谁、怎样才算对方接手。先准备参考资料，再把公司的具体分工告诉 AI。",
      "realLabel": "真实来源",
      "realTitle": "三份资料各用来做什么",
      "realIntro": "把它们作为 AI 编写流程的依据，也用来检查生成的内容。每份资料回答一个不同的问题。",
      "real1Title": "PF Group：小团队为什么也需要这个流程",
      "real1": "2022 年报告披露，当时有 19 名香港全职员工（包括董事），并已设投诉处理程序。这份资料用来说明：投诉处理也是小团队需要安排的工作。",
      "real2Title": "信达国际：一宗投诉通常经过哪些阶段",
      "real2": "公开流程包括受理、收件确认、调查、最终回复和后续反馈。用它了解整个流程，再决定这次 SOP 从哪里开始、写到哪里。",
      "real3Title": "SFC 附件：写完后要核对哪些要求",
      "real3": "22EC30 附件列出收到投诉后 7 天内确认收件、2 个月内最终回复，以及识别、升级和记录要求。用它检查 AI 有没有写错时限、漏掉应转交的事项或跟进记录。",
      "sourceUseTitle": "实际操作时，怎样把资料给 AI",
      "sourceUse": "材料包中已整理好《公开来源摘记》（01-public-source-notes.md）。建立 Grok 项目后，把它附在教练对话中；AI 问到参考材料时，就可以使用这份摘记。之后换新对话写 SOP，也要带上 Prompt 列明的材料。",
      "fictionLabel": "课堂设定",
      "fictionTitle": "Harbour Practice Securities",
      "fictionText": "假设这是一家 25 人的香港证券经纪公司，要给新来的运营人员写一份操作流程。这次公司、客户和业务材料均为虚构，岗位分工由下面的练习设定提供。",
      "rolesTitle": "先认清两个岗位",
      "roleHead1": "岗位名称",
      "roleHead2": "含义",
      "roleHead3": "本案例负责什么",
      "opsMeaning": "运营人员，Ops 是 Operations 的简称",
      "opsRole": "接收投诉、登记、收集材料、转交，并持续跟踪状态和期限。",
      "officerMeaning": "投诉处理负责人",
      "officerRole": "明确确认接手，安排负责人员和调查，组织后续处理。",
      "roleExample": "例如：客户把投诉发到客服邮箱，运营人员登记后转给投诉负责人。负责人明确回邮“我已接手”，并留下接手人和时间，才算完成交接。此时投诉可能还没有解决，运营人员仍要继续跟踪。",
      "scopeTitle": "这份 SOP 写到哪一步",
      "scopeText": "从收到投诉写到投诉负责人明确接手，并写清之后由运营人员继续跟踪状态和原期限。完整调查、赔偿决定、最终回信和最终归档属于后续流程。",
      "deadlineTitle": "给客户确认收件，要看哪个期限",
      "deadlineText": "练习公司希望在 2 个工作日内给客户确认收件；所给 SFC 资料写的是收到投诉起 7 天内。两者取较早期限。这里说的是给客户的收件确认，投诉负责人内部回邮“我已接手”是另一件事。",
      "s3": "3. 在 Grok 接入这位教练",
      "s3Intro": "先添加 skill，再建立项目并放入参考资料。下面把使用 skill 问清需求、生成 Prompt 的聊天称为“教练对话 A”。",
      "setup1Title": "上传 skill",
      "setup1": "工具 → 技能 → 新技能 → 上传技能文件。选择材料包 skills 文件夹里的 SKILL.md；如果界面要求 ZIP，先将该技能文件夹压缩后上传。",
      "setup2Title": "新建项目",
      "setup2": "项目命名“我的 SOP Prompt”。",
      "setup3Title": "附上公开来源摘记",
      "setup3": "在项目里打开一个新聊天，通过输入框旁“＋”上传 01-public-source-notes.md。这就是三份公开资料的摘记，接下来的问答会用到它。",
      "setup4Title": "选择技能，开始教练对话 A",
      "setup4": "输入框旁“＋” → 技能 → 选择 hk-sop-prompt-coach，再发送下一节的开场需求。它应该先提问，帮助你把需求说清楚。若直接交出 SOP，先检查本轮是否选中了技能。",
      "s4": "4. 跟着这段问答走",
      "s4Intro": "前五步在教练对话 A 中完成：你说需求、回答问题、修正并确认，AI 再生成 Prompt。第六步才把 Prompt 带到新对话 B 写 SOP；第七步把具体问题带回 A。每张卡片都标明了内容用在哪里。",
      "where1": "使用位置：教练对话 A。发送下面这句开场需求，然后等 AI 提问。",
      "where2": "使用位置：继续在教练对话 A 回答。根据 AI 问到的内容，选用下面的公司背景和补充信息。",
      "where3": "使用位置：教练对话 A。等 AI 复述需求后，发送这条修正，让它更新需求确认卡。",
      "where4": "使用位置：教练对话 A。读完更新后的需求确认卡，内容正确再发送下面这句确认。",
      "where5": "使用位置：从教练对话 A 复制它刚生成的完整 Prompt。下面展示的是成品示例，供你对照内容是否齐全。",
      "where6": "使用位置：新对话 B。把你得到的完整 Prompt 和它列明的参考材料一起发送，让 AI 编写 SOP。",
      "where7": "使用位置：教练对话 A。下面这条消息来自第 6 节的完整模拟：AI 把还没人接手的投诉写成了已结案，你要让教练改好 Prompt。",
      "scriptBadge": "练习对话",
      "step1Title": "先说一个不完整的需求",
      "step2Title": "回答它问到的缺口",
      "step3Title": "在确认前，改两件事",
      "step4Title": "看清最新版，再确认",
      "step5Title": "生成完整 Prompt",
      "step6Title": "使用新对话验证",
      "step7Title": "把具体问题带回来",
      "watch": "检查要点",
      "watch1": "应该先问：给谁用、从哪一步开始、做到哪里、参考什么。第一次就交出整份 SOP，说明本轮流程没有按预期开始。",
      "watch2": "公司分工与公开来源分开；未知年限继续留空。根据实际问题补充对应信息。",
      "watch3": "原先“做到最终回复和归档”改成“做到明确接手”；收件目标改成 2 个工作日并保留 7 天口径。AI 应先更新确认卡，不能把这条修正当成确认。",
      "watch4": "检查范围、接手、期限和待确认项都已更新，再发送确认。旧版还在要求最终回信，就先纠正，不急着进入下一步。",
      "watch5": "把这段 Prompt 单独拿出来读：能看出给谁用、写到哪一步、参考什么、怎样检查结果吗？如果只写“按上面说的做”，就让教练补齐具体要求。",
      "watch6": "不要在新对话再次选择这位 Prompt 教练。把完整 prompt 和它列明的材料一起带过去，观察 AI 是否可以直接编写 SOP。",
      "watch7": "把“第几步写错了”和“应该怎么做”一起告诉教练。第 6 节把旧 SOP、你的反馈、Prompt 修改和新 SOP 放在一起，可以直接对照。",
      "prevStep": "上一步",
      "nextStep": "下一步",
      "copy": "复制这段",
      "copied": "已复制",
      "copyFallback": "未能自动复制，请选中文字复制",
      "rawLanguage": "中文原稿",
      "secondAnswers": "时限、工具和异常的补充回答",
      "promptNote": "完整 prompt 示例（v1），包含已确认需求、来源摘要和验收条件。",
      "s5": "5. 使用新对话验证",
      "s5Intro": "教练对话 A 已经看过你的补充和修正，可能靠聊天记录猜到你要什么。现在打开新对话 B，只带上完整 Prompt 和指定材料，看它能不能直接写出符合要求的 SOP。",
      "fresh1": "打开一个普通新聊天，作为对话 B。这次不选择 Prompt 教练 skill，让 AI 按 Prompt 编写 SOP。",
      "fresh2": "从 A 复制刚生成的完整 Prompt，粘贴到 B，并附上它列明的文件，例如《公开来源摘记》。",
      "fresh3": "拿到 SOP 后，按下面六项逐条检查。遇到不符合要求的句子，保留原文，下一节会用它给教练反馈。",
      "checkTitle": "结果检查清单",
      "check1": "范围停在明确接手，没有扩成完整调查或最终回信。",
      "check2": "接手人确认、人名或岗位、确认时间都有位置。",
      "check3": "2 个工作日与 7 天分开，取较早；2 个月原期限仍被跟踪。",
      "check4": "缺资料、涉事员工、严重事项、无人接手都有下一步。",
      "check5": "保存年限等未定规则没有被自动补成数字。",
      "check6": "交接完成没有变成投诉结案，后续跟踪仍在。",
      "reset": "清空勾选",
      "s6": "6. 说清哪一处错，再改 Prompt",
      "s6Intro": "用一宗具体投诉走一遍：先看 AI 写错的第 3 步，再看你怎么反馈、教练怎么改 Prompt，以及新 SOP 应该怎样写。",
      "simLabel": "完整模拟 · 对话和结果均为教学编写",
      "simCaseTitle": "邮件发出去了，但还没人接手",
      "simCase": "上午 9:00 收到客户投诉。9:10，运营同事小林把邮件转给投诉负责人陈女士。到了 10:00，陈女士还没有回复，投诉也还没处理完。",
      "sim1Title": "01 · 对话 B：AI 写错了第 3 步",
      "simAI": "AI 回复 · 模拟节选",
      "simStepHead": "步骤",
      "simActionHead": "AI 写出的操作",
      "simBad1": "收到投诉后，登记收到时间和投诉内容。",
      "simBad2": "运营同事通过邮件，把投诉转给投诉负责人。",
      "simBad3": "邮件发出后，将交接状态填为“已交接”，投诉状态填为“已结案”，停止跟进。",
      "simProblem": "问题就在第 3 步：陈女士还没回信，小林却被要求把登记表填成“已交接、已结案”。照着做，这宗还没人接手的投诉就容易被漏掉。",
      "sim2Title": "02 · 回到对话 A：你这样指出问题",
      "sim2Intro": "把写错的那一步贴回教练对话，再告诉它应该怎么做。下面这条消息可以直接复制。",
      "sim3Title": "03 · 对话 A：教练把要求写进 Prompt",
      "simCoach": "明白。我会把“邮件已发出”“有人接手”“投诉已解决”分开，明确写出每种情况下登记表该填什么。下面是 Prompt 中改清楚的部分。",
      "simRule1": "邮件已转发，但负责人还没明确回邮接手：交接状态填写“待接手”，投诉状态填写“未结案”。运营人员继续跟进；无人接手时通知主管。",
      "simRule2": "负责人明确回邮接手后：记录接手人、接手时间和确认邮件的位置，才把交接状态改为“已交接”。投诉状态仍为“未结案”，运营人员继续跟踪原期限。",
      "simRule3": "把上面两种情况分别写进操作表和交接检查清单。保留其他已确认要求；所有期限仍从收到投诉起算，不从转发或接手时重新计算。",
      "simPromptTitle": "展开完整 Prompt v2 · 模拟修订版",
      "simPromptNote": "这里保留了 v1 的完整需求和来源，补清两种状态，并附上小林这宗投诉，让 AI 在 SOP 后示范两种情况下如何填写登记表。复制整段到普通新聊天即可试用，这次不用选择 Prompt 教练技能。",
      "sim4Title": "04 · 对话 C：新 SOP 把两种情况分开写",
      "sim4Intro": "把完整 Prompt v2 和相同材料放进新对话 C，让它生成 SOP，并用 Prompt 里附带的小林案例示范怎样填表。下面是模拟的新回复节选。",
      "simResultHead1": "这时发生了什么",
      "simResultHead2": "新 SOP 应该让小林这样做",
      "simPending": "10:00 · 陈女士还没回复",
      "simPendingResult": "交接状态：待接手。投诉状态：未结案。继续跟进，并通知主管。不能因为邮件已经发出就把事情划掉。",
      "simAccepted": "10:30 · 陈女士回邮“这宗投诉我来接手”",
      "simAcceptedResult": "记下接手人“陈女士”、时间“10:30”和确认邮件位置。交接状态改为“已交接”；投诉状态仍是“未结案”。继续跟踪从 9:00 收件起算的原期限。",
      "simTryTitle": "自己试一次，就检查这两行",
      "simTry": "用上面的完整 Prompt 生成一份 SOP，再分别代入“10:00 还没回复”和“10:30 已经接手”。看它能不能告诉你状态填什么、谁继续跟进。实际输出若仍有问题，就把那一行发回教练对话继续修改。",
      "s7": "7. 把题目换成自己的工作",
      "s7Intro": "挑一个入口清楚、每天或每周会重复、做完能检查的流程。先完成一小段，再逐步扩展。",
      "scenarioHead1": "岗位 / 场景",
      "scenarioHead2": "可以这样开口",
      "scenarioHead3": "先问清什么",
      "scenario1a": "Settlement · 入金凭证",
      "scenario1b": "“客户发来存款截图，新人不知道先核对什么。”",
      "scenario1c": "凭证、存款人、截止时点、异常交给谁。参考金利丰公开须知。",
      "scenario2a": "Ops · 提款指示受理",
      "scenario2b": "“不同币种的提款指示容易过截数时间。”",
      "scenario2c": "币种、实际渠道、公司时限和经办复核。页面没写的审批链要问。",
      "scenario3a": "Ops · 业务中断交接",
      "scenario3b": "“系统不能用时，新人不知道谁接手哪些工作。”",
      "scenario3c": "必要业务、备用安排、通知对象、恢复标准。具体规则由公司提供。",
      "scenario4a": "Compliance · 资料访问",
      "scenario4b": "“把谁能读取客户材料、怎么交接写清楚。”",
      "scenario4c": "访问权限、授权方式、存放位置、保存政策。未定的年限不猜。",
      "homework": "练习成果包括：原始需求、最终确认卡、完整 prompt 和一次试跑结果。标明一处需要人工复核的内容。",
      "s8": "8. 学习材料",
      "footer": "Week 4 · 先问清楚，再写 Prompt · 课堂虚构业务材料 · 来源查阅于 2026-09-10",
      "railKicker": "操作流程",
      "railTitle": "问清需求<br>验证结果",
      "rail1": "下载并接入技能",
      "rail2": "逐步复制发言",
      "rail3": "新对话检查六件事",
      "rail4": "带着具体错误回来",
      "railTip": "将已确认的需求、材料和验收条件写进 prompt，让新对话能够独立完成任务。",
      "railPlatform": "使用平台：Grok 网页版",
      "flowPlain": "收到投诉 → 运营人员登记、检查异常 → 转给投诉负责人 → 负责人明确接手 → 运营人员继续跟踪",
      "materialsIntro": "材料包只有 skills 和 materials 两个文件夹，包含技能文件、公开来源摘记和练习发言。"
    },
    "zh-TW": {
      "eyebrow": "Week 4 · Grok 網頁實操",
      "title": "先讓 AI 問清楚<br>再讓它寫 Prompt",
      "lead": "從一句“幫我寫個 SOP”開始，通過回答、修正和確認，把需求整理成可在新對話執行的 prompt。",
      "goal": "學習目標",
      "goalText": "使用 Prompt 教練 skill 整理需求，生成自己的 prompt，並在新對話中檢查結果。",
      "start": "開始練習",
      "downloadPack": "下載學員材料包",
      "nav1": "從需求到 Prompt",
      "nav2": "選一個有依據的 SOP",
      "nav3": "在 Grok 接入 skill",
      "nav4": "問答、修正與確認",
      "nav5": "使用新對話驗證",
      "nav6": "根據結果修改",
      "nav7": "換成自己的工作",
      "nav8": "學習材料",
      "s1": "1. 先説你要做什麼",
      "s1Intro": "Week 3 介紹了角色、背景、任務、格式和示例。讓 AI 幫你問清這些信息，再檢查它是否正確理解需求。",
      "s1Quote": "不用一開始就寫得專業。先把工作裏的麻煩説出來，再把 AI 理解偏的地方改回來。",
      "route1": "説需求",
      "route2": "AI 追問",
      "route3": "複述、修正",
      "route4": "用户確認",
      "route5": "生成 Prompt",
      "route6": "新對話驗證",
      "route7": "按結果修改",
      "s1Note": "skill（保存好的問答流程）讓 AI 按步驟幫你整理需求。檢查它是否問到關鍵缺口、保留需求修正，並讓新對話仍能讀到完整要求。",
      "s2": "2. 選一個能對照的流程",
      "s2Intro": "這次要寫的是“客户投訴接收與交接”。例如，客户把投訴發到客服郵箱，新人需要知道先登記什麼、交給誰、怎樣才算對方接手。先準備參考資料，再把公司的具體分工告訴 AI。",
      "realLabel": "真實來源",
      "realTitle": "三份資料各用來做什麼",
      "realIntro": "把它們作為 AI 編寫流程的依據，也用來檢查生成的內容。每份資料回答一個不同的問題。",
      "real1Title": "PF Group：小團隊為什麼也需要這個流程",
      "real1": "2022 年報告披露，當時有 19 名香港全職員工（包括董事），並已設投訴處理程序。這份資料用來説明：投訴處理也是小團隊需要安排的工作。",
      "real2Title": "信達國際：一宗投訴通常經過哪些階段",
      "real2": "公開流程包括受理、收件確認、調查、最終回覆和後續反饋。用它瞭解整個流程，再決定這次 SOP 從哪裏開始、寫到哪裏。",
      "real3Title": "SFC 附件：寫完後要核對哪些要求",
      "real3": "22EC30 附件列出收到投訴後 7 天內確認收件、2 個月內最終回覆，以及識別、升級和記錄要求。用它檢查 AI 有沒有寫錯時限、漏掉應轉交的事項或跟進記錄。",
      "sourceUseTitle": "實際操作時，怎樣把資料給 AI",
      "sourceUse": "材料包中已整理好《公開來源摘記》（01-public-source-notes.md）。建立 Grok 項目後，把它附在教練對話中；AI 問到參考材料時，就可以使用這份摘記。之後換新對話寫 SOP，也要帶上 Prompt 列明的材料。",
      "fictionLabel": "課堂設定",
      "fictionTitle": "Harbour Practice Securities",
      "fictionText": "假設這是一家 25 人的香港證券經紀公司，要給新來的運營人員寫一份操作流程。這次公司、客户和業務材料均為虛構，崗位分工由下面的練習設定提供。",
      "rolesTitle": "先認清兩個崗位",
      "roleHead1": "崗位名稱",
      "roleHead2": "含義",
      "roleHead3": "本案例負責什麼",
      "opsMeaning": "運營人員，Ops 是 Operations 的簡稱",
      "opsRole": "接收投訴、登記、收集材料、轉交，並持續跟蹤狀態和期限。",
      "officerMeaning": "投訴處理負責人",
      "officerRole": "明確確認接手，安排負責人員和調查，組織後續處理。",
      "roleExample": "例如：客户把投訴發到客服郵箱，運營人員登記後轉給投訴負責人。負責人明確回郵“我已接手”，並留下接手人和時間，才算完成交接。此時投訴可能還沒有解決，運營人員仍要繼續跟蹤。",
      "scopeTitle": "這份 SOP 寫到哪一步",
      "scopeText": "從收到投訴寫到投訴負責人明確接手，並寫清之後由運營人員繼續跟蹤狀態和原期限。完整調查、賠償決定、最終回信和最終歸檔屬於後續流程。",
      "deadlineTitle": "給客户確認收件，要看哪個期限",
      "deadlineText": "練習公司希望在 2 個工作日內給客户確認收件；所給 SFC 資料寫的是收到投訴起 7 天內。兩者取較早期限。這裏説的是給客户的收件確認，投訴負責人內部回郵“我已接手”是另一件事。",
      "s3": "3. 在 Grok 接入這位教練",
      "s3Intro": "先添加 skill，再建立項目並放入參考資料。下面把使用 skill 問清需求、生成 Prompt 的聊天稱為“教練對話 A”。",
      "setup1Title": "上傳 skill",
      "setup1": "工具 → 技能 → 新技能 → 上傳技能文件。選擇材料包 skills 文件夾裏的 SKILL.md；如果界面要求 ZIP，先將該技能文件夾壓縮後上傳。",
      "setup2Title": "新建項目",
      "setup2": "項目命名“我的 SOP Prompt”。",
      "setup3Title": "附上公開來源摘記",
      "setup3": "在項目裏打開一個新聊天，通過輸入框旁“＋”上傳 01-public-source-notes.md。這就是三份公開資料的摘記，接下來的問答會用到它。",
      "setup4Title": "選擇技能，開始教練對話 A",
      "setup4": "輸入框旁“＋” → 技能 → 選擇 hk-sop-prompt-coach，再發送下一節的開場需求。它應該先提問，幫助你把需求説清楚。若直接交出 SOP，先檢查本輪是否選中了技能。",
      "s4": "4. 跟着這段問答走",
      "s4Intro": "前五步在教練對話 A 中完成：你説需求、回答問題、修正並確認，AI 再生成 Prompt。第六步才把 Prompt 帶到新對話 B 寫 SOP；第七步把具體問題帶回 A。每張卡片都標明瞭內容用在哪裏。",
      "where1": "使用位置：教練對話 A。發送下面這句開場需求，然後等 AI 提問。",
      "where2": "使用位置：繼續在教練對話 A 回答。根據 AI 問到的內容，選用下面的公司背景和補充信息。",
      "where3": "使用位置：教練對話 A。等 AI 複述需求後，發送這條修正，讓它更新需求確認卡。",
      "where4": "使用位置：教練對話 A。讀完更新後的需求確認卡，內容正確再發送下面這句確認。",
      "where5": "使用位置：從教練對話 A 複製它剛生成的完整 Prompt。下面展示的是成品示例，供你對照內容是否齊全。",
      "where6": "使用位置：新對話 B。把你得到的完整 Prompt 和它列明的參考材料一起發送，讓 AI 編寫 SOP。",
      "where7": "使用位置：教練對話 A。下面這條消息來自第 6 節的完整模擬：AI 把還沒人接手的投訴寫成了已結案，你要讓教練改好 Prompt。",
      "scriptBadge": "練習對話",
      "step1Title": "先説一個不完整的需求",
      "step2Title": "回答它問到的缺口",
      "step3Title": "在確認前，改兩件事",
      "step4Title": "看清最新版，再確認",
      "step5Title": "生成完整 Prompt",
      "step6Title": "使用新對話驗證",
      "step7Title": "把具體問題帶回來",
      "watch": "檢查要點",
      "watch1": "應該先問：給誰用、從哪一步開始、做到哪裏、參考什麼。第一次就交出整份 SOP，説明本輪流程沒有按預期開始。",
      "watch2": "公司分工與公開來源分開；未知年限繼續留空。根據實際問題補充對應信息。",
      "watch3": "原先“做到最終回覆和歸檔”改成“做到明確接手”；收件目標改成 2 個工作日並保留 7 天口徑。AI 應先更新確認卡，不能把這條修正當成確認。",
      "watch4": "檢查範圍、接手、期限和待確認項都已更新，再發送確認。舊版還在要求最終回信，就先糾正，不急着進入下一步。",
      "watch5": "把這段 Prompt 單獨拿出來讀：能看出給誰用、寫到哪一步、參考什麼、怎樣檢查結果嗎？如果只寫“按上面説的做”，就讓教練補齊具體要求。",
      "watch6": "不要在新對話再次選擇這位 Prompt 教練。把完整 prompt 和它列明的材料一起帶過去，觀察 AI 是否可以直接編寫 SOP。",
      "watch7": "把“第幾步寫錯了”和“應該怎麼做”一起告訴教練。第 6 節把舊 SOP、你的反饋、Prompt 修改和新 SOP 放在一起，可以直接對照。",
      "prevStep": "上一步",
      "nextStep": "下一步",
      "copy": "複製這段",
      "copied": "已複製",
      "copyFallback": "未能自動複製，請選中文字複製",
      "rawLanguage": "中文原稿",
      "secondAnswers": "時限、工具和異常的補充回答",
      "promptNote": "完整 prompt 示例（v1），包含已確認需求、來源摘要和驗收條件。",
      "s5": "5. 使用新對話驗證",
      "s5Intro": "教練對話 A 已經看過你的補充和修正，可能靠聊天記錄猜到你要什麼。現在打開新對話 B，只帶上完整 Prompt 和指定材料，看它能不能直接寫出符合要求的 SOP。",
      "fresh1": "打開一個普通新聊天，作為對話 B。這次不選擇 Prompt 教練 skill，讓 AI 按 Prompt 編寫 SOP。",
      "fresh2": "從 A 複製剛生成的完整 Prompt，粘貼到 B，並附上它列明的文件，例如《公開來源摘記》。",
      "fresh3": "拿到 SOP 後，按下面六項逐條檢查。遇到不符合要求的句子，保留原文，下一節會用它給教練反饋。",
      "checkTitle": "結果檢查清單",
      "check1": "範圍停在明確接手，沒有擴成完整調查或最終回信。",
      "check2": "接手人確認、人名或崗位、確認時間都有位置。",
      "check3": "2 個工作日與 7 天分開，取較早；2 個月原期限仍被跟蹤。",
      "check4": "缺資料、涉事員工、嚴重事項、無人接手都有下一步。",
      "check5": "保存年限等未定規則沒有被自動補成數字。",
      "check6": "交接完成沒有變成投訴結案，後續跟蹤仍在。",
      "reset": "清空勾選",
      "s6": "6. 説清哪一處錯，再改 Prompt",
      "s6Intro": "用一宗具體投訴走一遍：先看 AI 寫錯的第 3 步，再看你怎麼反饋、教練怎麼改 Prompt，以及新 SOP 應該怎樣寫。",
      "simLabel": "完整模擬 · 對話和結果均為教學編寫",
      "simCaseTitle": "郵件發出去了，但還沒人接手",
      "simCase": "上午 9:00 收到客户投訴。9:10，運營同事小林把郵件轉給投訴負責人陳女士。到了 10:00，陳女士還沒有回覆，投訴也還沒處理完。",
      "sim1Title": "01 · 對話 B：AI 寫錯了第 3 步",
      "simAI": "AI 回覆 · 模擬節選",
      "simStepHead": "步驟",
      "simActionHead": "AI 寫出的操作",
      "simBad1": "收到投訴後，登記收到時間和投訴內容。",
      "simBad2": "運營同事通過郵件，把投訴轉給投訴負責人。",
      "simBad3": "郵件發出後，將交接狀態填為“已交接”，投訴狀態填為“已結案”，停止跟進。",
      "simProblem": "問題就在第 3 步：陳女士還沒回信，小林卻被要求把登記表填成“已交接、已結案”。照着做，這宗還沒人接手的投訴就容易被漏掉。",
      "sim2Title": "02 · 回到對話 A：你這樣指出問題",
      "sim2Intro": "把寫錯的那一步貼回教練對話，再告訴它應該怎麼做。下面這條消息可以直接複製。",
      "sim3Title": "03 · 對話 A：教練把要求寫進 Prompt",
      "simCoach": "明白。我會把“郵件已發出”“有人接手”“投訴已解決”分開，明確寫出每種情況下登記表該填什麼。下面是 Prompt 中改清楚的部分。",
      "simRule1": "郵件已轉發，但負責人還沒明確回郵接手：交接狀態填寫“待接手”，投訴狀態填寫“未結案”。運營人員繼續跟進；無人接手時通知主管。",
      "simRule2": "負責人明確回郵接手後：記錄接手人、接手時間和確認郵件的位置，才把交接狀態改為“已交接”。投訴狀態仍為“未結案”，運營人員繼續跟蹤原期限。",
      "simRule3": "把上面兩種情況分別寫進操作表和交接檢查清單。保留其他已確認要求；所有期限仍從收到投訴起算，不從轉發或接手時重新計算。",
      "simPromptTitle": "展開完整 Prompt v2 · 模擬修訂版",
      "simPromptNote": "這裏保留了 v1 的完整需求和來源，補清兩種狀態，並附上小林這宗投訴，讓 AI 在 SOP 後示範兩種情況下如何填寫登記表。複製整段到普通新聊天即可試用，這次不用選擇 Prompt 教練技能。",
      "sim4Title": "04 · 對話 C：新 SOP 把兩種情況分開寫",
      "sim4Intro": "把完整 Prompt v2 和相同材料放進新對話 C，讓它生成 SOP，並用 Prompt 裏附帶的小林案例示範怎樣填表。下面是模擬的新回覆節選。",
      "simResultHead1": "這時發生了什麼",
      "simResultHead2": "新 SOP 應該讓小林這樣做",
      "simPending": "10:00 · 陳女士還沒回復",
      "simPendingResult": "交接狀態：待接手。投訴狀態：未結案。繼續跟進，並通知主管。不能因為郵件已經發出就把事情劃掉。",
      "simAccepted": "10:30 · 陳女士回郵“這宗投訴我來接手”",
      "simAcceptedResult": "記下接手人“陳女士”、時間“10:30”和確認郵件位置。交接狀態改為“已交接”；投訴狀態仍是“未結案”。繼續跟蹤從 9:00 收件起算的原期限。",
      "simTryTitle": "自己試一次，就檢查這兩行",
      "simTry": "用上面的完整 Prompt 生成一份 SOP，再分別代入“10:00 還沒回復”和“10:30 已經接手”。看它能不能告訴你狀態填什麼、誰繼續跟進。實際輸出若仍有問題，就把那一行發回教練對話繼續修改。",
      "s7": "7. 把題目換成自己的工作",
      "s7Intro": "挑一個入口清楚、每天或每週會重複、做完能檢查的流程。先完成一小段，再逐步擴展。",
      "scenarioHead1": "崗位 / 場景",
      "scenarioHead2": "可以這樣開口",
      "scenarioHead3": "先問清什麼",
      "scenario1a": "Settlement · 入金憑證",
      "scenario1b": "“客户發來存款截圖，新人不知道先核對什麼。”",
      "scenario1c": "憑證、存款人、截止時點、異常交給誰。參考金利豐公開須知。",
      "scenario2a": "Ops · 提款指示受理",
      "scenario2b": "“不同幣種的提款指示容易過截數時間。”",
      "scenario2c": "幣種、實際渠道、公司時限和經辦複核。頁面沒寫的審批鏈要問。",
      "scenario3a": "Ops · 業務中斷交接",
      "scenario3b": "“系統不能用時，新人不知道誰接手哪些工作。”",
      "scenario3c": "必要業務、備用安排、通知對象、恢復標準。具體規則由公司提供。",
      "scenario4a": "Compliance · 資料訪問",
      "scenario4b": "“把誰能讀取客户材料、怎麼交接寫清楚。”",
      "scenario4c": "訪問權限、授權方式、存放位置、保存政策。未定的年限不猜。",
      "homework": "練習成果包括：原始需求、最終確認卡、完整 prompt 和一次試跑結果。標明一處需要人工複核的內容。",
      "s8": "8. 學習材料",
      "footer": "Week 4 · 先問清楚，再寫 Prompt · 課堂虛構業務材料 · 來源查閲於 2026-09-10",
      "railKicker": "操作流程",
      "railTitle": "問清需求<br>驗證結果",
      "rail1": "下載並接入技能",
      "rail2": "逐步複製發言",
      "rail3": "新對話檢查六件事",
      "rail4": "帶着具體錯誤回來",
      "railTip": "將已確認的需求、材料和驗收條件寫進 prompt，讓新對話能夠獨立完成任務。",
      "railPlatform": "使用平台：Grok 網頁版",
      "flowPlain": "收到投訴 → 運營人員登記、檢查異常 → 轉給投訴負責人 → 負責人明確接手 → 運營人員繼續跟蹤",
      "materialsIntro": "材料包只有 skills 和 materials 兩個文件夾，包含技能文件、公開來源摘記和練習發言。"
    },
    "en": {
      "eyebrow": "Week 4 · Using Grok on the web",
      "title": "Let AI ask first<br>Then write the prompt",
      "lead": "Start with “help me write an SOP”. Answer questions, correct the brief and confirm it to create a prompt that works in a fresh chat.",
      "goal": "Learning objective",
      "goalText": "Use a prompt-coach skill to clarify your needs, generate your own prompt and check its output in a fresh chat.",
      "start": "Start the exercise",
      "downloadPack": "Download learner pack",
      "nav1": "From request to prompt",
      "nav2": "Start with a sourced process",
      "nav3": "Add the skill in Grok",
      "nav4": "Ask, correct, confirm",
      "nav5": "Validate in a fresh chat",
      "nav6": "Revise from evidence",
      "nav7": "Use your own workflow",
      "nav8": "Learning materials",
      "s1": "1. Start with what you need",
      "s1Intro": "Week 3 introduced role, context, task, format and example. Let AI ask for these details, then check whether it has understood your needs.",
      "s1Quote": "You do not need a polished brief to begin. Describe the friction in your work, then correct what the AI gets wrong.",
      "route1": "Describe",
      "route2": "AI asks questions",
      "route3": "Restate and correct",
      "route4": "Confirm",
      "route5": "Get a prompt",
      "route6": "Validate in a fresh chat",
      "route7": "Revise",
      "s1Note": "A skill is a saved workflow that helps AI clarify your brief step by step. Check that it asks about important gaps, preserves your corrections and carries the complete requirements into a fresh chat.",
      "s2": "2. Choose a process you can check",
      "s2Intro": "Our case is receiving and handing off client complaints. A complaint arrives in the customer-service inbox: a new colleague needs to know what to record, who to send it to and how to know that person has accepted it. Gather the sources first, then tell the AI how the firm assigns the work.",
      "realLabel": "Real sources",
      "realTitle": "What each source is for",
      "realIntro": "Give these sources to the AI as a basis for the procedure, then use them to check its output. Each source answers a different question.",
      "real1Title": "PF Group: why a small team needs this process",
      "real1": "The 2022 report disclosed 19 full-time Hong Kong staff, including directors, and an established complaint-handling procedure. It provides the background for this case: small teams also need to organise complaint handling.",
      "real2Title": "Cinda: the stages a complaint goes through",
      "real2": "Its public process covers receipt, acknowledgement, investigation, a final response and further feedback. Use it to see the overall sequence, then decide where this SOP should start and end.",
      "real3Title": "SFC appendix: what to check in the draft",
      "real3": "The appendix to circular 22EC30 specifies acknowledgement within seven days of receipt and a final response within two months, along with identification, escalation and record-keeping requirements. Use it to check for incorrect deadlines, missing escalation steps and missing follow-up records.",
      "sourceUseTitle": "How to give the sources to the AI",
      "sourceUse": "The learner pack includes Public Source Notes (01-public-source-notes.md). After creating the Grok project, attach the notes to the coach chat so the AI can use them when clarifying the sources. When you move to a fresh chat to write the SOP, also supply the materials listed in the prompt.",
      "fictionLabel": "Classroom scenario",
      "fictionTitle": "Harbour Practice Securities",
      "fictionText": "Imagine a 25-person Hong Kong securities broker that needs a procedure for new operations staff. The firm, clients and business materials are fictional; the role assignments below are part of the exercise.",
      "rolesTitle": "Meet the two roles",
      "roleHead1": "Role",
      "roleHead2": "Meaning",
      "roleHead3": "Responsibilities in this case",
      "opsMeaning": "Operations staff; Ops is short for Operations",
      "opsRole": "Receive and log complaints, collect information, pass the case on and keep tracking its status and deadlines.",
      "officerMeaning": "The person responsible for handling complaints",
      "officerRole": "Explicitly accept the handoff, assign the work, arrange the investigation and coordinate further handling.",
      "roleExample": "For example, a complaint arrives in the customer-service inbox. Operations staff log it and send it to the Complaints Officer. The handoff is complete only after an explicit reply accepting it, with the receiving person and time recorded. The complaint may still be unresolved, so operations staff continue tracking it.",
      "scopeTitle": "Where this SOP ends",
      "scopeText": "Cover receipt through explicit acceptance by the Complaints Officer, and assign continued status and deadline tracking to operations staff. Full investigation, compensation decisions, final client letters and final archiving belong to the later process.",
      "deadlineTitle": "When to acknowledge receipt to the client",
      "deadlineText": "The fictional firm aims to acknowledge receipt to the client within two business days; the supplied SFC source says within seven days of receipt. Apply the earlier deadline. This is the acknowledgement sent to the client; the Complaints Officer’s internal reply accepting the case is a separate action.",
      "s3": "3. Add the coach in Grok",
      "s3Intro": "Add the skill, create a project and supply the sources. We will call the conversation that uses the skill to clarify your needs and generate the prompt “coach chat A”.",
      "setup1Title": "Upload the skill",
      "setup1": "Tools → Skills → New skill → Upload skill file. Select SKILL.md inside the learner pack’s skills folder; if a ZIP is required, compress that skill’s folder and upload it.",
      "setup2Title": "Create a project",
      "setup2": "Name the project “My SOP Prompt”.",
      "setup3Title": "Attach the public source notes",
      "setup3": "Open a new chat in the project and use + beside the message box to upload 01-public-source-notes.md. These notes summarise the three public sources for the conversation that follows.",
      "setup4Title": "Select the skill and start coach chat A",
      "setup4": "Use + beside the message box → Skills → hk-sop-prompt-coach, then send the opening request from the next section. It should ask questions to clarify your needs. If it immediately produces an SOP, check that the skill is selected for this chat.",
      "s4": "4. Walk through the conversation",
      "s4Intro": "Complete the first five steps in coach chat A: describe your needs, answer questions, correct and confirm the brief, then receive a prompt. In step six, take it to fresh chat B to write the SOP. In step seven, bring a specific issue back to A. Each card says where its content belongs.",
      "where1": "Where to use it: coach chat A. Send the opening request below, then wait for the AI’s questions.",
      "where2": "Where to use it: stay in coach chat A. Use the company background and additional answers below to respond to the questions the AI actually asks.",
      "where3": "Where to use it: coach chat A. After the AI restates the brief, send this correction so it updates the brief for your confirmation.",
      "where4": "Where to use it: coach chat A. Read the updated brief and send the confirmation below once it is correct.",
      "where5": "Where to use it: copy the complete prompt just generated in coach chat A. The example below shows what the finished prompt should contain.",
      "where6": "Where to use it: fresh chat B. Send the complete prompt you received, together with its listed sources, and let the AI write the SOP.",
      "where7": "Where to use it: coach chat A. This message belongs to the full simulation in section 6: the AI marked a complaint as closed before anyone accepted it, and you ask the coach to revise the prompt.",
      "scriptBadge": "Practice dialogue",
      "step1Title": "Start with an incomplete request",
      "step2Title": "Answer the important gaps",
      "step3Title": "Make two corrections before confirming",
      "step4Title": "Confirm the updated brief",
      "step5Title": "Generate the complete prompt",
      "step6Title": "Validate in a fresh chat",
      "step7Title": "Bring back a specific problem",
      "watch": "Checks",
      "watch1": "It should first ask about users, scope, boundaries and sources. A full SOP in the first reply means the coaching flow did not start as intended.",
      "watch2": "Keep company roles separate from public sources, and leave unknown retention periods open. Provide the information relevant to each question.",
      "watch3": "Change the endpoint from final response and archiving to accepted handoff; change the internal target to two business days while retaining seven days. The AI should update the brief, not treat this correction as approval.",
      "watch4": "Check scope, ownership, deadlines and open items before confirming. If a final client letter remains in the requirements, correct it first.",
      "watch5": "Read the prompt on its own. Does it say who the SOP is for, where it ends, what sources to use and how to check the result? If it only says “do what we agreed above”, ask the coach to include the actual requirements.",
      "watch6": "Do not select this prompt coach again in the new chat. Supply the whole prompt and listed materials, then see whether the AI can write the SOP directly.",
      "watch7": "Tell the coach which step is wrong and what should happen instead. Section 6 puts the old SOP, your feedback, the prompt revision and the new SOP together for comparison.",
      "prevStep": "Previous",
      "nextStep": "Next",
      "copy": "Copy message",
      "copied": "Copied",
      "copyFallback": "Select and copy the text manually",
      "rawLanguage": "Original Chinese text",
      "secondAnswers": "Additional answers: deadlines, tools and exceptions",
      "promptNote": "Complete prompt example (v1), including the confirmed brief, source summaries and acceptance criteria.",
      "s5": "5. Validate in a fresh chat",
      "s5Intro": "Coach chat A has seen your answers and corrections, so its history may fill in missing details. Open fresh chat B with the complete prompt and its specified materials, and check whether it can directly produce the SOP you need.",
      "fresh1": "Open an ordinary fresh chat as chat B. Leave the prompt-coach skill unselected so the AI can follow the prompt and write the SOP.",
      "fresh2": "Copy the complete prompt just generated in A, paste it into B and attach the files it lists, such as the public source notes.",
      "fresh3": "Check the resulting SOP against the six items below. Keep the exact wording of any sentence that fails a requirement; you will use it to give the coach feedback in the next section.",
      "checkTitle": "Output checklist",
      "check1": "The scope ends at accepted handoff, without adding full investigation or final client letters.",
      "check2": "There is a place for explicit acceptance, the receiving person or role, and the timestamp.",
      "check3": "Two business days and seven days remain distinct; the earlier applies, and the original two-month deadline is tracked.",
      "check4": "Missing information, implicated staff, serious cases and an unaccepted handoff each have a next action.",
      "check5": "Unknown retention periods and other unsettled rules have not been invented.",
      "check6": "Handoff is not complaint closure, and follow-up remains assigned.",
      "reset": "Reset checklist",
      "s6": "6. Name the problem, then revise the prompt",
      "s6Intro": "Follow one complaint through the whole revision: see the AI’s incorrect step 3, your feedback, the coach’s prompt changes and what the new SOP should say.",
      "simLabel": "Full simulation · All dialogue and results are written teaching examples",
      "simCaseTitle": "The email was sent, but no one has accepted the case",
      "simCase": "A client complaint arrives at 09:00. At 09:10, Lin in operations forwards it to Ms Chan, the Complaints Officer. At 10:00, Ms Chan has not replied and the complaint remains unresolved.",
      "sim1Title": "01 · Chat B: the AI gets step 3 wrong",
      "simAI": "AI reply · Simulated excerpt",
      "simStepHead": "Step",
      "simActionHead": "What the AI wrote",
      "simBad1": "Record when the complaint arrived and what it concerns.",
      "simBad2": "Operations staff forward the complaint to the Complaints Officer by email.",
      "simBad3": "After sending the email, set the handoff status to “Accepted” and the complaint status to “Closed”, then stop following up.",
      "simProblem": "The problem is step 3: Ms Chan has not replied, yet Lin is told to record the handoff as accepted and the complaint as closed. Following this instruction could leave the complaint unattended.",
      "sim2Title": "02 · Return to A: explain the problem like this",
      "sim2Intro": "Paste the incorrect step back into the coach chat and explain what should happen instead. You can copy the message below.",
      "sim3Title": "03 · Chat A: the coach makes the prompt explicit",
      "simCoach": "Understood. I will separate sending the email, someone accepting the case and the complaint being resolved, and specify what to record in each situation. Here is the part of the prompt I have clarified.",
      "simRule1": "If the email has been forwarded but the officer has not explicitly accepted by reply: record handoff status as “Awaiting acceptance” and complaint status as “Open”. Operations staff keep following up and notify their supervisor if no one accepts.",
      "simRule2": "After the officer explicitly accepts by reply: record the receiving person, time and location of the confirmation email before changing handoff status to “Accepted”. Complaint status remains “Open”, and operations staff keep tracking the original deadlines.",
      "simRule3": "Cover both situations in the procedure table and handoff checklist. Preserve the other confirmed requirements. All deadlines still run from receipt of the complaint, without restarting at forwarding or acceptance.",
      "simPromptTitle": "Expand the complete prompt v2 · Simulated revision",
      "simPromptNote": "This version retains the complete v1 brief and sources, clarifies both statuses and includes Lin’s complaint so the AI can show how to fill the register in both situations after writing the SOP. Copy the whole prompt into an ordinary fresh chat to try it, without selecting the prompt-coach skill.",
      "sim4Title": "04 · Chat C: the new SOP covers both situations",
      "sim4Intro": "Send the complete prompt v2 and the same materials to fresh chat C. Ask it to write the SOP and use Lin’s case, included in the prompt, to show how to fill the register. Below is a simulated excerpt from the new reply.",
      "simResultHead1": "What has happened",
      "simResultHead2": "What the new SOP tells Lin to do",
      "simPending": "10:00 · Ms Chan has not replied",
      "simPendingResult": "Handoff status: Awaiting acceptance. Complaint status: Open. Keep following up and notify the supervisor. Sending the email does not finish the task.",
      "simAccepted": "10:30 · Ms Chan replies, “I will take this complaint”",
      "simAcceptedResult": "Record Ms Chan as the receiving person, 10:30 as the acceptance time and the confirmation email’s location. Change handoff status to “Accepted”; complaint status remains “Open”. Keep tracking the original deadlines from receipt at 09:00.",
      "simTryTitle": "Try it yourself and check these two cases",
      "simTry": "Generate an SOP with the complete prompt above, then apply the two cases: no reply at 10:00 and acceptance at 10:30. Check whether it tells you what status to record and who continues following up. If the actual output still has a problem, take that line back to the coach for another revision.",
      "s7": "7. Swap in your own work",
      "s7Intro": "Pick a recurring process with a clear starting point and checkable completion. Finish a small part before expanding it.",
      "scenarioHead1": "Role / scenario",
      "scenarioHead2": "A natural starting request",
      "scenarioHead3": "What to clarify first",
      "scenario1a": "Settlement · deposit evidence",
      "scenario1b": "“Clients send deposit screenshots; new staff do not know what to check first.”",
      "scenario1c": "Evidence, payer identity, cut-offs and exception ownership. See Kingston’s public instructions.",
      "scenario2a": "Ops · withdrawal requests",
      "scenario2b": "“We keep missing the cut-offs for withdrawal requests in different currencies.”",
      "scenario2c": "Currency, channels, company deadlines and review roles. Ask about approval steps absent from the public page.",
      "scenario3a": "Ops · continuity handoff",
      "scenario3b": "“When a system is unavailable, new staff do not know who takes over.”",
      "scenario3c": "Essential work, fallback arrangements, contacts and recovery criteria. Obtain the firm’s actual rules.",
      "scenario4a": "Compliance · data access",
      "scenario4b": "“Document who can access client materials and how to hand them over.”",
      "scenario4c": "Access rights, authorisation, storage and retention policy. Do not guess an unsettled retention period.",
      "homework": "Save your original request, confirmed brief, complete prompt and one trial output. Identify one point that needs human review.",
      "s8": "8. Learning materials",
      "footer": "Week 4 · Ask first, then write the prompt · Fictional business materials · Sources accessed 10 September 2026",
      "railKicker": "Workflow",
      "railTitle": "Clarify the brief<br>Validate the result",
      "rail1": "Download and add the skill",
      "rail2": "Copy each message",
      "rail3": "Check six things in a fresh chat",
      "rail4": "Return with specific evidence",
      "railTip": "Include the confirmed brief, materials and acceptance criteria in the prompt so a fresh chat can complete the task independently.",
      "railPlatform": "Platform: Grok on the web",
      "flowPlain": "Complaint received → Operations logs it and checks for exceptions → Send it to the Complaints Officer → Officer explicitly accepts → Operations keeps tracking",
      "materialsIntro": "The pack has just two folders, skills and materials, containing the skill file, public source notes and practice messages."
    }
  },
  "payload": {
    "opening": "我们是香港一家二十多人的证券公司，客户投诉有时先找客户经理，有时发邮件，交接容易漏。帮我做个新人照着走的投诉处理 SOP。我不太会写 prompt，你先帮我把需求问清楚。",
    "answer1": "这是课堂虚构公司 Harbour Practice Securities，不对应真实客户。25 人，做香港证券经纪。给新来的 Ops 同事用，先按从收到投诉到最终回复、归档来考虑。入口是客户经理转交、客服邮箱和电话。Ops 负责登记、追材料和跟进；Complaints Officer 负责分派及调查；Compliance / MIC 处理严重事项、监管报告判断和复核。参考刚才的公开资料，不要假定我们有投诉委员会或专用系统。",
    "answer2": "登记和内部转交希望当天做。初稿先按参考里的 7 天收件确认、2 个月最终回复理解。我们用受限共享文件夹和投诉登记表。我要繁体中文的操作表，列清步骤、责任人、输入、动作、输出或留痕、时限、异常转交，再附一份交接检查清单。记录保存年限和外部报告的后备负责人暂时没定，留待确认，别替我们编。\n\n接手要有接收方明确回邮，并记录接手人、时间和邮件位置。对客收件确认由 Ops 跟踪，Complaints Officer 安排经授权人员发出；这是另一件事，不能把内部接手回邮当成对客收件确认。最终回复和结案的审批细节暂时没有提供。\n\n有资料缺口也要先登记和转交，不等齐件才计时。投诉涉及客户经理本人时，他只能补事实，不能独自调查或批准。遇到未授权交易、疑似挪用客户资产等严重事项，Ops 立即转 Complaints Officer 和 Compliance / MIC；有紧急或监管报告事项不能等普通内部流转结束。没有任何一方确认接手时，Ops 继续跟进并通知主管，不能把登记状态改成已交接。阶段性更新的具体频率也留给 Complaints Officer 确认。",
    "correction": "改两点：这次先不写完整调查、赔偿决定、最终回信和最终归档，只做到 Complaints Officer 明确接手；Ops 之后保留状态和期限跟踪。还有，收件确认的内部目标改为 2 个工作日，同时不能晚于收到起 7 天，遇到长假取较早期限；2 个月最终回复仍在登记表里跟踪。别把“交接完成”写成“投诉结案”。请先更新需求确认卡，让我再确认。",
    "confirmation": "确认，按这版生成 prompt。记录保存年限、阶段性更新频率、外部报告的后备负责人继续写待确认。其他尚未提供的实施细节也保留待确认，不要拿来阻止草稿生成。这里的岗位和内部目标都是课堂虚构设定。请只给可以在新对话使用的完整 prompt 和需要携带的材料，先不要写 SOP。",
    "prompt": "版本：v1\n\n你是香港證券經紀公司的流程文件編寫助手。請直接為下列課堂虛構公司編寫一份供人覆核的投訴接收與交接 SOP 草稿，使用繁體中文，保留公司名稱與英文崗位名稱。\n\n需求已由使用者確認，請直接生成草稿，不要重新進行需求訪談。未提供的實施細節以「[待確認：事項 / 負責崗位]」標示；負責崗位也未知時，寫「負責崗位待公司指定」。不要因這些已接受的待確認項停止生成。只有必要材料確實缺失、依據互相衝突，或使用者後續改變需求時，才針對該問題詢問。\n\n一、業務背景與本次範圍\n\n1. Harbour Practice Securities 是一家 25 人、從事香港證券經紀的課堂虛構公司，不對應真實客戶。下列崗位、工具和內部目標都是使用者確認的課堂虛構設定，不是真實公司的制度。\n2. 使用者是新入職的 Ops 同事，文字要讓新人知道下一步做甚麼、交給誰、留下甚麼證據，以及遇到異常找誰。\n3. 投訴入口只有本次確認的三類：客戶經理轉交、客服郵箱、電話。\n4. 主流程從收到投訴開始，到 Complaints Officer 明確回郵確認接手，並記錄接手人和接手時間為止。此後 Ops 保留狀態和期限跟蹤，包括收件確認及最終回覆期限。\n5. 本次不編寫完整調查、賠償決定、最終回信或最終歸檔流程；不要生成相應信件、調查報告、賠償批准表或最終歸檔清單。\n6. 「受理投訴」不等於確認投訴成立；「交接完成」不等於「投訴結案」。最終回覆期限的跟蹤，不表示本次要撰寫最終回覆。\n7. 不預設投訴委員會、專用投訴系統或其他未確認崗位。本次使用受限共享文件夾和投訴登記表。\n\n二、已確認的公司做法與責任邊界\n本節全部屬於課堂虛構設定，請與後面的外部依據分開標示。\n\n1. Ops：\n   - 當天登記投訴並作內部轉交，記錄入口、收到日期及時間、事件與訴求、已有資料及缺口、責任人、狀態、期限和跟進留痕。\n   - 資料不齊也要先登記、轉交和追材料，不得把「資料齊全」設為登記或轉交的前提。\n   - 跟蹤收件確認，由 Complaints Officer 安排經授權人員發出；不要把 Ops 寫成可自行批准或發出收件確認的人。\n   - 主動追蹤是否有人接手。無人接手時，Ops 繼續跟進並通知主管。\n   - 交接後繼續記錄狀態及期限，不能因已轉交便停止跟蹤。\n   - 不賦予 Ops 調查批准、賠償、最終回覆批准或結案權限。\n2. Complaints Officer：\n   - 負責分派及調查，但本次只展開接手、相關交接和收件確認安排，不編寫完整調查程序。\n   - 必須明確回郵確認接手；登記表須記下接手人、接手時間及確認郵件的留痕位置。\n   - 安排經授權人員發出收件確認。\n3. Compliance / MIC：\n   - 處理嚴重事項、監管報告判斷和覆核。是否需要外部報告、向誰報告及如何履行，必須由適當人員依適用要求判斷，不能交由 AI 或 Ops 自行決定。\n4. 客戶經理：\n   - 可轉交投訴及補充事實。\n   - 投訴涉及該客戶經理本人時，他只能補充事實，不能獨自調查或批准。\n5. 嚴重事項：\n   - 立即交 Complaints Officer 和 Compliance / MIC。\n   - 不得因等待資料齊全、等待接手、內部審批或正常流轉而延誤必要的升級及報告判斷。\n6. 交接完成：\n   - 以接收方明確回郵確認接手，並記錄接手人和時間為完成標準。\n   - 僅寄出轉交郵件、存入共享文件夾或完成登記，都不等於已有人接手。\n   - 未齊資料和仍待完成的客戶收件確認，要作為待辦列明並繼續跟蹤，不能因此阻止先登記和轉交。\n   - 客戶收件確認或最終回覆是否已完成，不是本次內部交接完成的前置條件。\n   - 清楚區分「Complaints Officer 對內確認接手的郵件」與「經授權人員向客戶發出的收件確認」。\n7. 普通逾期的具體轉交安排尚未提供。仍須寫出 Ops 持續跟蹤和記錄的動作，將未定的轉交對象及實施細節標為待確認，不自行編造時限、批准人或自動延期規則。\n\n三、期限：分清內部目標與所給外部依據\n\n1. 當天登記及內部轉交：公司已確認的課堂內部目標。\n2. 收件確認：\n   - 公司內部目標：收到投訴起 2 個工作日內。\n   - 所給監管參考：收到投訴之日起 7 天內。\n   - 本練習採用兩者中較早的到期日，即「較早者：收到起 2 個工作日／收到起 7 天」；遇長假亦然，不能突破收到起 7 天的上限。\n   - 保留「2 個工作日」和「7 天」各自的原單位，不能把 7 天改為 7 個工作日，也不能只寫其中一項。\n3. 最終回覆：投訴登記表繼續跟蹤收到投訴起 2 個月的期限。保留「2 個月」，不要換算為 60 天或 60 個工作日；本次不撰寫最終回信。\n4. 投訴處理期限從收到投訴起算，不因 Ops 登記、內部轉交或接手確認重新起算。記錄中要區分收到時間、登記時間、轉交時間和接手時間。\n5. 在相關操作表的「輸出或留痕」中說清需要保留的期限資料：收到日期及時間、2 個工作日目標、7 天上限、較早的適用期限、收件確認發出狀態及證據、2 個月最終回覆期限及跟蹤狀態。\n6. 工作日定義、假日日曆及具体日期計算口徑尚未提供，保留待確認。沒有具體收件日期或適用日曆時，不編造實際到期日期；仍須完整寫出較早期限規則，不能用這個缺口取消 7 天上限或阻止草稿生成。\n7. 階段性更新頻率未定，不自行設定每日、每週或其他固定頻率。\n\n四、本次材料與可使用的來源摘要\n\n以下必要摘要已內嵌，使本提示詞可在沒有舊對話的情況下使用。可同時附上唯一業務材料「01-public-source-notes.md」，標題為《公開來源摘記：客戶投訴流程》，檢索日期 2026-09-10，供核對。\n如未附原始摘記，使用下列內嵌摘要；不要聲稱已閱讀未提供的原文或已核驗網頁。本次不需要教練 skill、原對話或其他課堂資料，不聯網、不操作外部系統。\n\nR1：監管參考\n來源：SFC，2022-03-31，通函 22EC30《Handling of client complaints》及附件。\n正文：\nhttps://apps.sfc.hk/edistributionWeb/api/circular/list-content/circular/intermediaries/supervision/doc?lang=EN&refNo=22EC30\n附件：\nhttps://apps.sfc.hk/edistributionWeb/api/circular/openAppendix?appendix=0&lang=EN&refNo=22EC30\n\n提供的內容是自寫摘記，不是原文全文：\n- 附件 A.4（PDF 第 1 頁）：收件確認應在收到投訴之日起 7 天內發出；最終回覆應在 2 個月內發出。\n- 附件 C（第 3–4 頁）：辨別投訴與一般查詢；嚴重、高影響事件及時升級；疑似違反相關監管要求的報告不能等調查結束。不是每宗服務投訴都要報 SFC。\n- 附件 A.9、D（第 2、5 頁）：由適當人員客觀調查，處理利益衝突；制定結案和解決方案的審批安排。本次只保留相關邊界，不展開範圍以外的調查、解決方案或結案流程。\n- 附件 F（第 7 頁）：維護投訴及跟進記錄，制定適當保存政策。摘記未提供統一保存年限。\n使用限制：只依據所給版本，不能宣稱已完整審查所有現行法規或已確認現行適用性；實務採用前由公司合規確認適用版本。不要添加沒有來源的條文、期限或報告要求。\n\nR2：其他券商的公開流程參考\n來源：信達國際控股有限公司《投訴處理程序》。\nhttps://www.cinda.com.hk/tc/complaint_policy.php?id=0\n公開流程包含電話、郵件及書信受理；收集事件、疑慮、訴求及聯絡方式；7 天內確認收件並開展調查；2 個月內給出調查結果及擬採取行動的最終回覆；對結果不滿可繼續反映或尋求 FDRC 協助。\n這是其他券商的客戶流程，不是 Harbour Practice Securities 的內部制度，也不是本公司的崗位分工依據。不要據此新增書信入口、調查程序、最終回信或其他本次未確認的交付內容。\n\nR3：小團隊的歷史背景參考\n來源：PF Group Holdings Limited《2022 Environmental, Social and Governance Report》。\nhttps://www.gyf.com.hk/wp-content/uploads/2024/08/cw_08221ESG-11082022.pdf\n第 19 頁披露截至 2022-03-31 有 19 名香港全職員工，包括董事；第 30 頁說明合規手冊設有投訴處理程序。\n這只是歷史背景，不能聲稱該公司目前仍有 19 人，也不能聲稱已取得其未公開內部手冊。Harbour Practice Securities 的 25 人規模及崗位安排來自本提示詞的課堂虛構設定。\n\n寫作時分清：\n- 有出處的外部依據：保留來源、日期、章節、原期限單位及适用限制。\n- 使用者已確認的公司做法：始終標明為課堂虛構設定。\n- 其他券商做法或 AI 的組織建議：只作參考；若提出額外建議，標明「建議／待公司確認」，不得升格為既定制度。\n\n五、輸出要求\n\n請按以下順序交付，重點放在操作表和交接檢查清單，不擴展為其他文書：\n\n1. 簡短的文件資訊及範圍說明：\n   - 標明課堂虛構、供人覆核的草稿。\n   - 寫清主流程終點和 Ops 交接後保留的跟蹤責任。\n   - SOP 作者、批准人、生效日未提供，標為待確認。\n2. 繁體中文操作表，必須使用且完整保留以下七列：\n   「步驟｜責任人｜輸入｜動作｜輸出或留痕｜時限｜異常轉交」。\n   - 主流程覆蓋三類入口的接收、初步辨別、登記、資料缺口、內部轉交、接手確認及留痕。\n   - 對投訴與一般查詢難以辨別之處，標明需要人員判斷，不以 AI 自動判定作為拒絕登記的理由。\n   - 另外清楚標出交接後 Ops 的狀態及期限跟蹤動作，使主流程終點不被悄悄延長至結案。\n   - 每行寫清由誰做、需要甚麼、做甚麼、留下甚麼證據、何時做及異常轉交；未知細節明確標待確認。\n   - 覆蓋資料不齊、無人接手、逾期、涉及客戶經理本人的利益衝突，以及嚴重事項。\n   - 使用投訴登記表和受限共享文件夾保存本階段記錄及交接證據，不把這些留痕描述為最終歸檔。\n3. 交接檢查清單：\n   - 用可勾選的條目列出判斷是否已完成交接的必要證據，包含接收方明確回郵、接手人、接手時間及郵件留痕位置。\n   - 區分「交接完成所需證據」與「交接後仍需跟蹤的事項」，避免把所有待辦已完成當成交接的門檻。\n   - 缺資料需列明缺口及跟進狀態；收件確認和最終回覆期限需保留跟蹤。\n   - 不要求資料全部齊備、客戶收件確認已發出或最終回覆已完成才准轉交。\n   - 清楚寫明交接完成不代表投訴結案。\n4. 簡短列出尚待確認的事項：\n   - 記錄保存年限。\n   - 階段性更新頻率。\n   - 外部報告後備負責人。\n   - 工作日定義、假日日曆及日期計算口徑。\n   - 普通逾期的具體轉交安排。\n   - SOP 作者、批准人和生效日。\n   - 其他未提供的實施細節及相應負責崗位。\n   最終回覆和結案審批細節屬於本次範圍以外，不得把它們當成草稿生成的前置條件。\n5. 簡短來源說明，標出 R1 的日期及相關章節，說明 R2、R3 的參考性質及本次沒有核驗現行適用性。\n\n六、逐條驗收條件\n\n交付前用下列條件檢查並修正草稿：\n1. 清楚標明課堂虛構公司、25 人、香港證券經紀及新 Ops 讀者。\n2. 只做到 Complaints Officer 明確接手，之後只有 Ops 狀態及期限跟蹤；沒有完整調查、賠償決定、最終回信或最終歸檔交付物。\n3. 操作表以繁體中文呈現並保留指定七列，另有可勾選的交接檢查清單。\n4. 三類入口齊全；當天登記和內部轉交；資料不齊也先登記、轉交並追材料。\n5. 接手完成有明確回郵、接手人及時間證據；沒有「寄出即完成」或「交接即結案」。\n6. Ops 跟蹤收件確認，Complaints Officer 安排經授權人員發出；沒有擅自增加 Ops 的發送、調查批准、賠償或結案權限。\n7. 收件確認同時寫明內部 2 個工作日與收到起 7 天上限，採較早期限，長假亦適用；2 個月最終回覆保留原單位並繼續跟蹤。\n8. 無人接手時 Ops 持續跟進並通知主管；普通逾期未定細節如實標示，沒有杜撰新的內部時限。\n9. 涉事客戶經理只能補充事實，不能獨自調查或批准。\n10. 嚴重事項立即交 Complaints Officer 和 Compliance / MIC，不以等材料、等調查完成或內部流轉延誤報告判斷，也沒有把每宗服務投訴都寫成必須報 SFC。\n11. 使用已確認的登記表及受限共享文件夾，沒有自行增設委員會或專用系統。\n12. 記錄保存年限、階段性更新頻率、外部報告後備負責人及其他未定細節均保留待確認，未因它們停止輸出。\n13. 外部依據、課堂公司做法及建議明確區分，來源日期、章節和期限單位可核對，沒有宣稱法規全面或最新。\n\n必要的驗收反例：\n- 「等客戶補齊資料後才登記或轉交」不合格。\n- 「Ops 寄出轉交郵件便標記投訴結案」不合格。\n- 「只需在 2 個工作日內收件確認，因此长假可超過收到起 7 天」不合格。\n- 「本次不寫最終回信，但仍附最終回信模板或最終歸檔清單」不合格。\n\n只使用字段名稱和虛構代號，不索取真實客戶身份證、帳戶號或完整客戶檔案。本任務僅編写文件，不連接客戶系統、不發送郵件、不執行資金或交易操作。現在請直接輸出符合上述要求的 SOP 草稿。\n",
    "feedback": "我们用下面这段模拟结果练习改 Prompt：小林把投诉邮件转给陈女士，但陈女士还没回复。\n\nAI 写的第 3 步是：“邮件发出后，将交接状态填为‘已交接’，投诉状态填为‘已结案’，停止跟进。”\n\n第 3 步改一下：邮件发出去后，先写“待接手”。对方明确回邮接手，并记下接手人、时间和邮件位置后，才写“已交接”。\n\n投诉这时还没处理完，要继续写“未结案”，由运营同事跟踪原来的期限。还没人接手时，继续跟进并通知主管。\n\n请把这些要求写进完整 Prompt，其他正确要求保留。给我完整新版，方便我放到新对话再生成一份 SOP。",
    "simPrompt": "版本：v2（本節模擬修訂版）\n\n你是香港證券經紀公司的流程文件編寫助手。請直接為下列課堂虛構公司編寫一份供人覆核的投訴接收與交接 SOP 草稿，使用繁體中文，保留公司名稱與英文崗位名稱。\n\n需求已由使用者確認，請直接生成草稿，不要重新進行需求訪談。未提供的實施細節以「[待確認：事項 / 負責崗位]」標示；負責崗位也未知時，寫「負責崗位待公司指定」。不要因這些已接受的待確認項停止生成。只有必要材料確實缺失、依據互相衝突，或使用者後續改變需求時，才針對該問題詢問。\n\n一、業務背景與本次範圍\n\n1. Harbour Practice Securities 是一家 25 人、從事香港證券經紀的課堂虛構公司，不對應真實客戶。下列崗位、工具和內部目標都是使用者確認的課堂虛構設定，不是真實公司的制度。\n2. 使用者是新入職的 Ops 同事，文字要讓新人知道下一步做甚麼、交給誰、留下甚麼證據，以及遇到異常找誰。\n3. 投訴入口只有本次確認的三類：客戶經理轉交、客服郵箱、電話。\n4. 主流程從收到投訴開始，到 Complaints Officer 明確回郵確認接手，並記錄接手人和接手時間為止。此後 Ops 保留狀態和期限跟蹤，包括收件確認及最終回覆期限。\n5. 本次不編寫完整調查、賠償決定、最終回信或最終歸檔流程；不要生成相應信件、調查報告、賠償批准表或最終歸檔清單。\n6. 「受理投訴」不等於確認投訴成立；「交接完成」不等於「投訴結案」。最終回覆期限的跟蹤，不表示本次要撰寫最終回覆。\n7. 不預設投訴委員會、專用投訴系統或其他未確認崗位。本次使用受限共享文件夾和投訴登記表。\n\n二、已確認的公司做法與責任邊界\n本節全部屬於課堂虛構設定，請與後面的外部依據分開標示。\n\n1. Ops：\n   - 當天登記投訴並作內部轉交，記錄入口、收到日期及時間、事件與訴求、已有資料及缺口、責任人、狀態、期限和跟進留痕。\n   - 資料不齊也要先登記、轉交和追材料，不得把「資料齊全」設為登記或轉交的前提。\n   - 跟蹤收件確認，由 Complaints Officer 安排經授權人員發出；不要把 Ops 寫成可自行批准或發出收件確認的人。\n   - 主動追蹤是否有人接手。無人接手時，Ops 繼續跟進並通知主管。\n   - 交接後繼續記錄狀態及期限，不能因已轉交便停止跟蹤。\n   - 不賦予 Ops 調查批准、賠償、最終回覆批准或結案權限。\n2. Complaints Officer：\n   - 負責分派及調查，但本次只展開接手、相關交接和收件確認安排，不編寫完整調查程序。\n   - 必須明確回郵確認接手；登記表須記下接手人、接手時間及確認郵件的留痕位置。\n   - 安排經授權人員發出收件確認。\n3. Compliance / MIC：\n   - 處理嚴重事項、監管報告判斷和覆核。是否需要外部報告、向誰報告及如何履行，必須由適當人員依適用要求判斷，不能交由 AI 或 Ops 自行決定。\n4. 客戶經理：\n   - 可轉交投訴及補充事實。\n   - 投訴涉及該客戶經理本人時，他只能補充事實，不能獨自調查或批准。\n5. 嚴重事項：\n   - 立即交 Complaints Officer 和 Compliance / MIC。\n   - 不得因等待資料齊全、等待接手、內部審批或正常流轉而延誤必要的升級及報告判斷。\n6. 交接完成：\n   - 以接收方明確回郵確認接手，並記錄接手人和時間為完成標準。\n   - 僅寄出轉交郵件、存入共享文件夾或完成登記，都不等於已有人接手。\n   - 未齊資料和仍待完成的客戶收件確認，要作為待辦列明並繼續跟蹤，不能因此阻止先登記和轉交。\n   - 客戶收件確認或最終回覆是否已完成，不是本次內部交接完成的前置條件。\n   - 清楚區分「Complaints Officer 對內確認接手的郵件」與「經授權人員向客戶發出的收件確認」。\n7. 普通逾期的具體轉交安排尚未提供。仍須寫出 Ops 持續跟蹤和記錄的動作，將未定的轉交對象及實施細節標為待確認，不自行編造時限、批准人或自動延期規則。\n\n三、期限：分清內部目標與所給外部依據\n\n1. 當天登記及內部轉交：公司已確認的課堂內部目標。\n2. 收件確認：\n   - 公司內部目標：收到投訴起 2 個工作日內。\n   - 所給監管參考：收到投訴之日起 7 天內。\n   - 本練習採用兩者中較早的到期日，即「較早者：收到起 2 個工作日／收到起 7 天」；遇長假亦然，不能突破收到起 7 天的上限。\n   - 保留「2 個工作日」和「7 天」各自的原單位，不能把 7 天改為 7 個工作日，也不能只寫其中一項。\n3. 最終回覆：投訴登記表繼續跟蹤收到投訴起 2 個月的期限。保留「2 個月」，不要換算為 60 天或 60 個工作日；本次不撰寫最終回信。\n4. 投訴處理期限從收到投訴起算，不因 Ops 登記、內部轉交或接手確認重新起算。記錄中要區分收到時間、登記時間、轉交時間和接手時間。\n5. 在相關操作表的「輸出或留痕」中說清需要保留的期限資料：收到日期及時間、2 個工作日目標、7 天上限、較早的適用期限、收件確認發出狀態及證據、2 個月最終回覆期限及跟蹤狀態。\n6. 工作日定義、假日日曆及具体日期計算口徑尚未提供，保留待確認。沒有具體收件日期或適用日曆時，不編造實際到期日期；仍須完整寫出較早期限規則，不能用這個缺口取消 7 天上限或阻止草稿生成。\n7. 階段性更新頻率未定，不自行設定每日、每週或其他固定頻率。\n\n四、本次材料與可使用的來源摘要\n\n以下必要摘要已內嵌，使本提示詞可在沒有舊對話的情況下使用。可同時附上唯一業務材料「01-public-source-notes.md」，標題為《公開來源摘記：客戶投訴流程》，檢索日期 2026-09-10，供核對。\n如未附原始摘記，使用下列內嵌摘要；不要聲稱已閱讀未提供的原文或已核驗網頁。本次不需要教練 skill、原對話或其他課堂資料，不聯網、不操作外部系統。\n\nR1：監管參考\n來源：SFC，2022-03-31，通函 22EC30《Handling of client complaints》及附件。\n正文：\nhttps://apps.sfc.hk/edistributionWeb/api/circular/list-content/circular/intermediaries/supervision/doc?lang=EN&refNo=22EC30\n附件：\nhttps://apps.sfc.hk/edistributionWeb/api/circular/openAppendix?appendix=0&lang=EN&refNo=22EC30\n\n提供的內容是自寫摘記，不是原文全文：\n- 附件 A.4（PDF 第 1 頁）：收件確認應在收到投訴之日起 7 天內發出；最終回覆應在 2 個月內發出。\n- 附件 C（第 3–4 頁）：辨別投訴與一般查詢；嚴重、高影響事件及時升級；疑似違反相關監管要求的報告不能等調查結束。不是每宗服務投訴都要報 SFC。\n- 附件 A.9、D（第 2、5 頁）：由適當人員客觀調查，處理利益衝突；制定結案和解決方案的審批安排。本次只保留相關邊界，不展開範圍以外的調查、解決方案或結案流程。\n- 附件 F（第 7 頁）：維護投訴及跟進記錄，制定適當保存政策。摘記未提供統一保存年限。\n使用限制：只依據所給版本，不能宣稱已完整審查所有現行法規或已確認現行適用性；實務採用前由公司合規確認適用版本。不要添加沒有來源的條文、期限或報告要求。\n\nR2：其他券商的公開流程參考\n來源：信達國際控股有限公司《投訴處理程序》。\nhttps://www.cinda.com.hk/tc/complaint_policy.php?id=0\n公開流程包含電話、郵件及書信受理；收集事件、疑慮、訴求及聯絡方式；7 天內確認收件並開展調查；2 個月內給出調查結果及擬採取行動的最終回覆；對結果不滿可繼續反映或尋求 FDRC 協助。\n這是其他券商的客戶流程，不是 Harbour Practice Securities 的內部制度，也不是本公司的崗位分工依據。不要據此新增書信入口、調查程序、最終回信或其他本次未確認的交付內容。\n\nR3：小團隊的歷史背景參考\n來源：PF Group Holdings Limited《2022 Environmental, Social and Governance Report》。\nhttps://www.gyf.com.hk/wp-content/uploads/2024/08/cw_08221ESG-11082022.pdf\n第 19 頁披露截至 2022-03-31 有 19 名香港全職員工，包括董事；第 30 頁說明合規手冊設有投訴處理程序。\n這只是歷史背景，不能聲稱該公司目前仍有 19 人，也不能聲稱已取得其未公開內部手冊。Harbour Practice Securities 的 25 人規模及崗位安排來自本提示詞的課堂虛構設定。\n\n寫作時分清：\n- 有出處的外部依據：保留來源、日期、章節、原期限單位及适用限制。\n- 使用者已確認的公司做法：始終標明為課堂虛構設定。\n- 其他券商做法或 AI 的組織建議：只作參考；若提出額外建議，標明「建議／待公司確認」，不得升格為既定制度。\n\n五、輸出要求\n\n請按以下順序交付，重點放在操作表和交接檢查清單，不擴展為其他文書：\n\n1. 簡短的文件資訊及範圍說明：\n   - 標明課堂虛構、供人覆核的草稿。\n   - 寫清主流程終點和 Ops 交接後保留的跟蹤責任。\n   - SOP 作者、批准人、生效日未提供，標為待確認。\n2. 繁體中文操作表，必須使用且完整保留以下七列：\n   「步驟｜責任人｜輸入｜動作｜輸出或留痕｜時限｜異常轉交」。\n   - 主流程覆蓋三類入口的接收、初步辨別、登記、資料缺口、內部轉交、接手確認及留痕。\n   - 對投訴與一般查詢難以辨別之處，標明需要人員判斷，不以 AI 自動判定作為拒絕登記的理由。\n   - 另外清楚標出交接後 Ops 的狀態及期限跟蹤動作，使主流程終點不被悄悄延長至結案。\n   - 每行寫清由誰做、需要甚麼、做甚麼、留下甚麼證據、何時做及異常轉交；未知細節明確標待確認。\n   - 覆蓋資料不齊、無人接手、逾期、涉及客戶經理本人的利益衝突，以及嚴重事項。\n   - 使用投訴登記表和受限共享文件夾保存本階段記錄及交接證據，不把這些留痕描述為最終歸檔。\n3. 交接檢查清單：\n   - 用可勾選的條目列出判斷是否已完成交接的必要證據，包含接收方明確回郵、接手人、接手時間及郵件留痕位置。\n   - 區分「交接完成所需證據」與「交接後仍需跟蹤的事項」，避免把所有待辦已完成當成交接的門檻。\n   - 缺資料需列明缺口及跟進狀態；收件確認和最終回覆期限需保留跟蹤。\n   - 不要求資料全部齊備、客戶收件確認已發出或最終回覆已完成才准轉交。\n   - 清楚寫明交接完成不代表投訴結案。\n4. 簡短列出尚待確認的事項：\n   - 記錄保存年限。\n   - 階段性更新頻率。\n   - 外部報告後備負責人。\n   - 工作日定義、假日日曆及日期計算口徑。\n   - 普通逾期的具體轉交安排。\n   - SOP 作者、批准人和生效日。\n   - 其他未提供的實施細節及相應負責崗位。\n   最終回覆和結案審批細節屬於本次範圍以外，不得把它們當成草稿生成的前置條件。\n5. 簡短來源說明，標出 R1 的日期及相關章節，說明 R2、R3 的參考性質及本次沒有核驗現行適用性。\n\n六、逐條驗收條件\n\n交付前用下列條件檢查並修正草稿：\n1. 清楚標明課堂虛構公司、25 人、香港證券經紀及新 Ops 讀者。\n2. 只做到 Complaints Officer 明確接手，之後只有 Ops 狀態及期限跟蹤；沒有完整調查、賠償決定、最終回信或最終歸檔交付物。\n3. 操作表以繁體中文呈現並保留指定七列，另有可勾選的交接檢查清單。\n4. 三類入口齊全；當天登記和內部轉交；資料不齊也先登記、轉交並追材料。\n5. 接手完成有明確回郵、接手人及時間證據；沒有「寄出即完成」或「交接即結案」。\n6. Ops 跟蹤收件確認，Complaints Officer 安排經授權人員發出；沒有擅自增加 Ops 的發送、調查批准、賠償或結案權限。\n7. 收件確認同時寫明內部 2 個工作日與收到起 7 天上限，採較早期限，長假亦適用；2 個月最終回覆保留原單位並繼續跟蹤。\n8. 無人接手時 Ops 持續跟進並通知主管；普通逾期未定細節如實標示，沒有杜撰新的內部時限。\n9. 涉事客戶經理只能補充事實，不能獨自調查或批准。\n10. 嚴重事項立即交 Complaints Officer 和 Compliance / MIC，不以等材料、等調查完成或內部流轉延誤報告判斷，也沒有把每宗服務投訴都寫成必須報 SFC。\n11. 使用已確認的登記表及受限共享文件夾，沒有自行增設委員會或專用系統。\n12. 記錄保存年限、階段性更新頻率、外部報告後備負責人及其他未定細節均保留待確認，未因它們停止輸出。\n13. 外部依據、課堂公司做法及建議明確區分，來源日期、章節和期限單位可核對，沒有宣稱法規全面或最新。\n\n必要的驗收反例：\n- 「等客戶補齊資料後才登記或轉交」不合格。\n- 「Ops 寄出轉交郵件便標記投訴結案」不合格。\n- 「只需在 2 個工作日內收件確認，因此长假可超過收到起 7 天」不合格。\n- 「本次不寫最終回信，但仍附最終回信模板或最終歸檔清單」不合格。\n\n只使用字段名稱和虛構代號，不索取真實客戶身份證、帳戶號或完整客戶檔案。本任務僅編写文件，不連接客戶系統、不發送郵件、不執行資金或交易操作。現在請直接輸出符合上述要求的 SOP 草稿。\n\n七、本節模擬修訂：分開記錄交接狀態與投訴狀態\n\n1. 郵件已轉發，但負責人還沒明確回郵接手：交接狀態填寫“待接手”，投訴狀態填寫“未結案”。運營人員繼續跟進；無人接手時通知主管。\n2. 負責人明確回郵接手後：記錄接手人、接手時間和確認郵件的位置，才把交接狀態改為“已交接”。投訴狀態仍為“未結案”，運營人員繼續跟蹤原期限。\n3. 把上面兩種情況分別寫進操作表和交接檢查清單。保留其他已確認要求；所有期限仍從收到投訴起算，不從轉發或接手時重新計算。\n\n八、本節模擬練習：用同一宗投訴示範怎樣填表\n\n上午 9:00 收到客户投訴。9:10，運營同事小林把郵件轉給投訴負責人陳女士。到了 10:00，陳女士還沒有回覆，投訴也還沒處理完。\n10:30，陳女士回郵“這宗投訴我來接手”。\n\n完成上述 SOP 後，再用兩行示範這兩種情況下如何填寫投訴登記表：10:00 還沒回復；10:30 已明確回郵接手。保留“情況｜交接狀態｜投訴狀態｜接手人、時間及確認郵件位置｜運營人員下一步”五列。沒有回郵時不要虛構接手人或接手時間；回郵後的郵件位置用“[填寫實際郵件位置]”表示，不編造文件或郵件證據。\n\n這些人物和時間只用於本節模擬，不能變成公司的處理時限或固定人員安排。只展示如何沿用原期限，不因沒有具體日期和假日日曆而編造到期日期。\n"
  }
};
