window.WEEK5_DATA = {
  "copy": {
    "zh-CN": {
      "eyebrow": "Week 5 · 模型、上下文与长文件",
      "title": "选对模型<br>给对材料",
      "lead": "翻译一封邮件、比较几条规则、读一份长报告，需要的模型和材料各不相同。这周从这些常见任务出发，学会选模型、给材料，再检查结果。",
      "goal": "本周目标",
      "goalText": "认清常见模型的区别，知道什么时候值得用旗舰，再用一份真实长报告，看看整理材料会带来什么变化。",
      "duration": "15 分钟 · 概念与实验",
      "nav1": "先认清几类模型",
      "nav2": "思考强度改了什么",
      "nav3": "装得下，为什么仍会漏",
      "s1": "1. 先认清几类模型",
      "s1Intro": "选模型时，先看四件事：怎么使用、能读什么、擅长多难的任务、能不能多花时间思考。下面把它们放到实际工作里看。",
      "modelTitle": "常见名字，认个脸熟",
      "modelDate": "常见厂商与模型示例 · 2026-09-17。先认清系列，使用时再看具体型号。",
      "vendorHead": "厂商",
      "familyHead": "常见产品 / 系列",
      "modelHead": "模型示例",
      "openaiModels": "GPT-6 Astra、GPT-5.6 系列",
      "anthropicModels": "Sonnet 5、Opus 5、Fable 5.1",
      "googleModels": "3.8 Flash、3.1 Pro（预览版）",
      "alibaba": "阿里巴巴",
      "qwen": "通义千问 / Qwen",
      "productNote": "Week 4 用过的 Grok 也在这里。聊天产品是使用入口，模型是里面负责理解和生成内容的部分。",
      "s2": "2. 思考强度，改的是这次花多少工夫",
      "s2Intro": "有些模型可以调低、中、高思考强度。调高以后，模型会花更多计算时间拆解问题、检查条件，再给出答案。",
      "paramHead1": "看到的词",
      "paramHead2": "可以怎样理解",
      "paramHead3": "对你有什么影响",
      "param1Name": "参数量 · 27B / 70B",
      "param1Meaning": "把模型想成一台有很多“小旋钮”的机器。训练会根据大量例子反复调好这些旋钮；参数量就是旋钮的数量。27B 约有 270 亿个。",
      "param1Effect": "旋钮越多，可以调整和组合的方式也越多，运行时通常需要更多内存和计算资源。",
      "param2Name": "上下文窗口 · 128K / 1M tokens",
      "param2Meaning": "这次工作能容纳多少信息。",
      "param2Effect": "决定一次能带上多少材料和聊天记录。",
      "param3Name": "最大输出长度",
      "param3Meaning": "一次最多能写多少。",
      "param3Effect": "长报告可能要分次生成。",
      "param4Name": "思考强度",
      "param4Meaning": "给复杂问题多少计算时间。",
      "param4Effect": "复杂问题可以多做几步检查，等待时间也会增加。",
      "param5Name": "Temperature · 随机程度",
      "param5Meaning": "影响生成答案时的变化程度。",
      "param5Effect": "改写、创意任务可尝试不同设置；日常使用先用默认值。",
      "paramNote": "参数量随模型选定；思考强度、输出长度等选项，则是使用时可以调整的设置。",
      "s3": "3. 上下文，像这次工作的桌面",
      "s3Intro": "Week 2 讲过 token：模型处理信息时使用的计量单位。上下文窗口，就是这次能容纳多少信息。",
      "deskLabel": "同一张桌子，两种材料摆法",
      "desk1": "便签 · 当前问题",
      "desk1Note": "现在要做什么",
      "desk2": "笔记 · 聊天记录",
      "desk2Note": "前面说过什么",
      "desk3": "文件 · 提供的材料",
      "desk3Note": "文件、图片、资料",
      "deskQuote": "桌子大，能摆更多东西；不代表每一页都会被同样仔细地用上。",
      "contextWhy": "模型回答时，会挑出与当前问题有关的信息，再把这些信息连起来。桌上堆满材料以后，找重点、分清相似内容、记住前后条件，都会变得更难。",
      "minutes": "分钟",
      "openTitle": "开源与闭源：自己部署，还是直接使用",
      "openIntro": "开源模型可以下载下来，由自己或公司部署和调整；闭源模型由厂商提供服务，通过网页或 API 就能使用。",
      "openH1": "看什么",
      "openH2": "开源模型",
      "openH3": "闭源模型",
      "open1a": "使用方式",
      "open1b": "下载模型，按自己的需要部署和调整。",
      "open1c": "打开聊天产品，或接入厂商提供的接口。",
      "open2a": "运行与维护",
      "open2b": "自己准备机器、部署和维护，也可以找托管服务。",
      "open2c": "厂商负责运行与更新，用户按订阅或用量付费。",
      "open3a": "常见用途",
      "open3b": "公司内网知识库、专用业务工具、模型定制。",
      "open3c": "日常写作、翻译、分析，以及快速接入 AI 功能。",
      "openNote": "公司有技术团队，希望把内部资料放在自己的服务器上处理，可以考虑开源模型。个人每天改邮件、整理纪要，直接使用现成的聊天服务更省事。",
      "modalityTitle": "纯文本与多模态：手里的材料是什么",
      "textPath": "文字 → 分成 tokens → 模型理解和生成 → 文字答案",
      "visionPath": "图片 → 视觉编码器提取特征 → 和问题一起处理 → 答案",
      "modalityBody": "纯文本模型处理文字。多模态模型能处理图片、声音等其他信息。以看图为例，常见做法是把图片切成小块，通过视觉编码器提取文字、形状和位置，再和你的问题一起处理。",
      "modalityExample": "例如，同一张走势图，提取出来的文字只有日期和数字；看图的模型还能利用曲线走势、颜色和交叉位置，理解你问的是哪一段变化。",
      "modalityNote": "改邮件，用文字模型就够了；读扫描件、看图表，选能看图的；整理录音，选支持音频的。",
      "fastTitle": "轻量模型和旗舰模型",
      "fastBody": "请专家来做一道小学题，当然能做，但多花的时间和费用未必值得。翻译邮件、改写句子、提取明确字段，快速模型通常就够用；任务里有多条规则、例外和取舍时，再让旗舰试试。",
      "fastNote": "Flash、Lite、mini 这类名称通常主打速度和成本。旗舰往往愿意花更多计算处理复杂任务，适合减少难题中的漏项和返工。",
      "thinkFlow": "读问题 → 拆成几步 → 检查条件与候选答案 → 给出结果",
      "thinkBody": "这些中间推导也会生成 tokens，所以需要时间和计算资源。调高强度时，模型的参数和学过的知识没有变，只是这次回答多做了一些推导；最后给你的答案仍然可以很短。",
      "thinkControls": "界面里的这些选项，分别管什么",
      "thinkH1": "选项",
      "thinkH2": "实际作用",
      "think1a": "思考模式 · 开 / 关",
      "think1b": "决定先做中间推导，还是直接回答。",
      "think2a": "思考强度 · 低 / 中 / 高",
      "think2b": "告诉模型，这道题值得花多少工夫。",
      "think3a": "思考预算",
      "think3b": "给中间推导设一个用量上限，用来控制等待和费用。",
      "paramTitle": "顺手认清几个常见参数",
      "context1Title": "相近的信息容易串在一起",
      "context1": "报告里同时出现试验尺寸、估算尺寸和假设尺寸。模型可能找到了数字，却把它放到了另一个事件上。",
      "context2Title": "隔得很远的条件容易漏",
      "context2": "前面写一般标准，后面写特殊情况。回答时要把两处内容合起来，中间再夹着几十页其他讨论，就更容易只记住其中一边。",
      "context3Title": "旧对话会把方向带偏",
      "context3": "一件事聊了很多轮，需求改过几次，旧要求和新要求还在同一段历史里。模型接着回答时，可能又沿用了已经作废的设定。",
      "contextGuideTitle": "实际工作时，先放多少材料",
      "contextGuideBody": "日常使用时，上下文最好控制在 300K tokens 左右以内；模型窗口更小时，以它的上限为准。",
      "thinkExample": "翻译一句普通邮件，可以直接答；核对几条互相牵连的规则，可以打开思考。先用中档，看看漏项有没有减少，再决定要不要继续提高。",
      "fastQuestion": "为什么不直接选最强的模型？",
      "fastCost": "如果每天要翻译几百段文字、处理几百条记录，每次多等一点、多花一点，累积起来就是时间和预算。选型时，把答案质量、等待时间和使用费用一起看。",
      "fastExampleTitle": "例如：翻译一个网页",
      "fastExample": "假设一次网页翻译中，旗舰开启较高思考强度，花了几分钟；轻量模型几秒就给出译文，两份译文的质量却没有明显差别。这时，用轻量模型就能更快、更省钱地完成工作。",
      "open4a": "调参 / 微调",
      "open4b": "用公司的标准问答、文书范例继续训练，让它更熟悉业务术语、固定格式和回答风格。",
      "open4c": "通过提示词和设置调整回答；部分服务也提供微调功能。",
      "deskImageAlt": "两张同样大小的桌面：左边摊满文件，关键句被其他纸张遮住；右边保留问题、聊天记录和相关资料，关键句清楚地露出来。",
      "deskWholeTitle": "材料都放得下",
      "deskWholeText": "纸张层层叠着，关键一句也可能被埋住。",
      "deskSelectedTitle": "把这次要用的摆出来",
      "deskSelectedText": "问题和相关证据放在一起，更容易找到重点。",
      "compareTitle": "同一道题，试试两个模型",
      "compareIntro": "先翻译邮件，再找出题目里的坑，最后破解密码。问题逐渐变难，答案仍然一眼就能核对。",
      "compareSetup": "选一个轻量模型和一个旗舰模型，例如 Qwen3.8-27B 与 Qwen3.8-Max。每题开新对话，发送相同内容，保持相同思考模式，不开启联网或代码工具。",
      "compareInput": "发给两个模型的同一道题",
      "compareCopy": "复制题目",
      "compareCopied": "已复制",
      "compareCopySuccess": "已复制，可以粘贴到模型对话中。",
      "compareCopyFallback": "请选中下方题目，手动复制。",
      "compareReference": "展开答案，现场核对",
      "compareConclusion": "两边都答对，就比较速度和费用；难题出现差距时，再看旗舰多花的时间是否值得。",
      "nav4": "长报告与一页原文",
      "nav5": "下次工作时，先这样选",
      "s4": "4. 做个对比：长报告与一页原文",
      "s4Intro": "开两个对话，用同一个模型。一个上传长报告，一个只上传相关的一页。两边问同样的问题，再追问一次，最后对照答案。",
      "longSetup": "A、B 两个新对话选同一个模型，思考模式保持一致。分别上传下面的 PDF，等上传完成后再提问。",
      "rawLanguage": "题目与参考答案 · 中文原稿",
      "rawInputLanguage": "演示输入 · 中文原稿",
      "copyQuestion": "复制问题",
      "groundHead1": "核对点",
      "groundHead2": "正确内容",
      "groundHead3": "原文页",
      "s5": "5. 下次工作时，先这样选",
      "chooseHead1": "遇到的情况",
      "chooseHead2": "先做什么",
      "choose1Situation": "改文字、做简单整理",
      "choose1Action": "先用快速或默认模型。",
      "choose2Situation": "问题复杂、需要比较多条条件",
      "choose2Action": "先补全条件，再比较旗舰或思考模式是否减少漏项与返工。",
      "choose3Situation": "材料是截图、扫描件或声音",
      "choose3Action": "选支持这种输入的模型。",
      "choose4Situation": "文档很长、聊天已经很乱",
      "choose4Action": "长文先找相关章节、保留附注和例外；旧对话整理好重点，再开新对话。",
      "choose5Situation": "核对金额、转账或作最终审批",
      "choose5Action": "金额核对用表格或计算工具；转账与最终审批由人确认。",
      "closingLabel": "今天带走",
      "closing": "简单任务看效率，复杂任务看增益，长文任务看证据。",
      "downloadDemo": "下载材料 + 问题包",
      "downloadLanguage": "包含长报告 PDF、单页 PDF、两轮提问和参考答案。解压后照着“怎么测”操作即可。",
      "longStory": "材料来自 NASA《哥伦比亚事故调查报告》。事故后，NASA 推演过：如果更早发现损伤，宇航员能否等待救援，或者修补后返回？我们就用这段真实材料，看看模型会不会找错数字、把假设说成事实。",
      "longStep1": "第一步：各上传一份 PDF",
      "longFileTitle": "A · 上传长报告",
      "longFileSize": "200 页 · 149.43 MB",
      "longFileHint": "把前 200 页整份传进去，让模型自己找。",
      "singleFileTitle": "B · 只上传相关的一页",
      "singleFileSize": "1 页 · 0.72 MB",
      "singleFileHint": "只传原报告第 173 页，两轮答案都在这里。",
      "downloadLongPdf": "下载长报告 PDF",
      "downloadSinglePdf": "下载单页 PDF",
      "longCropNote": "原报告共 248 页。演示版去掉末尾 48 页，保留前 200 页，文件低于 150 MB。本次问题不涉及删去的内容，保留页的正文、图表和页码不变。",
      "longStep2": "第二步：先问，还能在轨待多久？",
      "longFirstHint": "把下面这段原样发给 A 和 B，等两边都回答。",
      "longStep3": "第三步：追问，修补就一定能回来吗？",
      "longFollowHint": "直接在刚才的两个对话里继续发下面这段，不用重新上传 PDF。",
      "longFirstAnswer": "展开第 1 轮答案 · 3 项",
      "longFollowAnswer": "展开第 2 轮答案 · 3 项",
      "sourcePageLabel": "原报告第",
      "longStep4": "第四步：对答案，看差别",
      "longScore": "展开每轮下方的参考答案，答对一项记 1 分，两轮共 6 分。第一轮看数字有没有串，第二轮看有没有把假设当事实、把高风险说成有保证。意思正确即可，不要求措辞一样。",
      "longResult": "先看两边各答对几项，再看花了多久。两边都答对，就记录这次没有正确率差距；单页是否更快，也值得比较。"
    },
    "zh-TW": {
      "eyebrow": "Week 5 · 模型、上下文與長文件",
      "title": "選對模型<br>給對材料",
      "lead": "翻譯一封郵件、比較幾條規則、讀一份長報告，需要的模型和材料各不相同。這周從這些常見任務出發，學會選模型、給材料，再檢查結果。",
      "goal": "本週目標",
      "goalText": "認清常見模型的區別，知道什麼時候值得用旗艦，再用一份真實長報告，看看整理材料會帶來什麼變化。",
      "duration": "15 分鐘 · 概念與實驗",
      "nav1": "先認清幾類模型",
      "nav2": "思考強度改了什麼",
      "nav3": "裝得下，為什麼仍會漏",
      "s1": "1. 先認清幾類模型",
      "s1Intro": "選模型時，先看四件事：怎麼使用、能讀什麼、擅長多難的任務、能不能多花時間思考。下面把它們放到實際工作裏看。",
      "modelTitle": "常見名字，認個臉熟",
      "modelDate": "常見廠商與模型示例 · 2026-09-17。先認清系列，使用時再看具體型號。",
      "vendorHead": "廠商",
      "familyHead": "常見產品 / 系列",
      "modelHead": "模型示例",
      "openaiModels": "GPT-6 Astra、GPT-5.6 系列",
      "anthropicModels": "Sonnet 5、Opus 5、Fable 5.1",
      "googleModels": "3.8 Flash、3.1 Pro（預覽版）",
      "alibaba": "阿里巴巴",
      "qwen": "通義千問 / Qwen",
      "productNote": "Week 4 用過的 Grok 也在這裏。聊天產品是使用入口，模型是裏面負責理解和生成內容的部分。",
      "s2": "2. 思考強度，改的是這次花多少工夫",
      "s2Intro": "有些模型可以調低、中、高思考強度。調高以後，模型會花更多計算時間拆解問題、檢查條件，再給出答案。",
      "paramHead1": "看到的詞",
      "paramHead2": "可以怎樣理解",
      "paramHead3": "對你有什麼影響",
      "param1Name": "參數量 · 27B / 70B",
      "param1Meaning": "把模型想成一台有很多“小旋鈕”的機器。訓練會根據大量例子反覆調好這些旋鈕；參數量就是旋鈕的數量。27B 約有 270 億個。",
      "param1Effect": "旋鈕越多，可以調整和組合的方式也越多，運行時通常需要更多內存和計算資源。",
      "param2Name": "上下文窗口 · 128K / 1M tokens",
      "param2Meaning": "這次工作能容納多少信息。",
      "param2Effect": "決定一次能帶上多少材料和聊天記錄。",
      "param3Name": "最大輸出長度",
      "param3Meaning": "一次最多能寫多少。",
      "param3Effect": "長報告可能要分次生成。",
      "param4Name": "思考強度",
      "param4Meaning": "給複雜問題多少計算時間。",
      "param4Effect": "複雜問題可以多做幾步檢查，等待時間也會增加。",
      "param5Name": "Temperature · 隨機程度",
      "param5Meaning": "影響生成答案時的變化程度。",
      "param5Effect": "改寫、創意任務可嘗試不同設置；日常使用先用默認值。",
      "paramNote": "參數量隨模型選定；思考強度、輸出長度等選項，則是使用時可以調整的設置。",
      "s3": "3. 上下文，像這次工作的桌面",
      "s3Intro": "Week 2 講過 token：模型處理信息時使用的計量單位。上下文窗口，就是這次能容納多少信息。",
      "deskLabel": "同一張桌子，兩種材料擺法",
      "desk1": "便籤 · 當前問題",
      "desk1Note": "現在要做什麼",
      "desk2": "筆記 · 聊天記錄",
      "desk2Note": "前面説過什麼",
      "desk3": "文件 · 提供的材料",
      "desk3Note": "文件、圖片、資料",
      "deskQuote": "桌子大，能擺更多東西；不代表每一頁都會被同樣仔細地用上。",
      "contextWhy": "模型回答時，會挑出與當前問題有關的信息，再把這些信息連起來。桌上堆滿材料以後，找重點、分清相似內容、記住前後條件，都會變得更難。",
      "minutes": "分鐘",
      "openTitle": "開源與閉源：自己部署，還是直接使用",
      "openIntro": "開源模型可以下載下來，由自己或公司部署和調整；閉源模型由廠商提供服務，通過網頁或 API 就能使用。",
      "openH1": "看什麼",
      "openH2": "開源模型",
      "openH3": "閉源模型",
      "open1a": "使用方式",
      "open1b": "下載模型，按自己的需要部署和調整。",
      "open1c": "打開聊天產品，或接入廠商提供的接口。",
      "open2a": "運行與維護",
      "open2b": "自己準備機器、部署和維護，也可以找託管服務。",
      "open2c": "廠商負責運行與更新，用户按訂閲或用量付費。",
      "open3a": "常見用途",
      "open3b": "公司內網知識庫、專用業務工具、模型定製。",
      "open3c": "日常寫作、翻譯、分析，以及快速接入 AI 功能。",
      "openNote": "公司有技術團隊，希望把內部資料放在自己的服務器上處理，可以考慮開源模型。個人每天改郵件、整理紀要，直接使用現成的聊天服務更省事。",
      "modalityTitle": "純文本與多模態：手裏的材料是什麼",
      "textPath": "文字 → 分成 tokens → 模型理解和生成 → 文字答案",
      "visionPath": "圖片 → 視覺編碼器提取特徵 → 和問題一起處理 → 答案",
      "modalityBody": "純文本模型處理文字。多模態模型能處理圖片、聲音等其他信息。以看圖為例，常見做法是把圖片切成小塊，通過視覺編碼器提取文字、形狀和位置，再和你的問題一起處理。",
      "modalityExample": "例如，同一張走勢圖，提取出來的文字只有日期和數字；看圖的模型還能利用曲線走勢、顏色和交叉位置，理解你問的是哪一段變化。",
      "modalityNote": "改郵件，用文字模型就夠了；讀掃描件、看圖表，選能看圖的；整理錄音，選支持音頻的。",
      "fastTitle": "輕量模型和旗艦模型",
      "fastBody": "請專家來做一道小學題，當然能做，但多花的時間和費用未必值得。翻譯郵件、改寫句子、提取明確字段，快速模型通常就夠用；任務裏有多條規則、例外和取捨時，再讓旗艦試試。",
      "fastNote": "Flash、Lite、mini 這類名稱通常主打速度和成本。旗艦往往願意花更多計算處理複雜任務，適合減少難題中的漏項和返工。",
      "thinkFlow": "讀問題 → 拆成幾步 → 檢查條件與候選答案 → 給出結果",
      "thinkBody": "這些中間推導也會生成 tokens，所以需要時間和計算資源。調高強度時，模型的參數和學過的知識沒有變，只是這次回答多做了一些推導；最後給你的答案仍然可以很短。",
      "thinkControls": "界面裏的這些選項，分別管什麼",
      "thinkH1": "選項",
      "thinkH2": "實際作用",
      "think1a": "思考模式 · 開 / 關",
      "think1b": "決定先做中間推導，還是直接回答。",
      "think2a": "思考強度 · 低 / 中 / 高",
      "think2b": "告訴模型，這道題值得花多少工夫。",
      "think3a": "思考預算",
      "think3b": "給中間推導設一個用量上限，用來控制等待和費用。",
      "paramTitle": "順手認清幾個常見參數",
      "context1Title": "相近的信息容易串在一起",
      "context1": "報告裏同時出現試驗尺寸、估算尺寸和假設尺寸。模型可能找到了數字，卻把它放到了另一個事件上。",
      "context2Title": "隔得很遠的條件容易漏",
      "context2": "前面寫一般標準，後面寫特殊情況。回答時要把兩處內容合起來，中間再夾着幾十頁其他討論，就更容易只記住其中一邊。",
      "context3Title": "舊對話會把方向帶偏",
      "context3": "一件事聊了很多輪，需求改過幾次，舊要求和新要求還在同一段歷史裏。模型接着回答時，可能又沿用了已經作廢的設定。",
      "contextGuideTitle": "實際工作時，先放多少材料",
      "contextGuideBody": "日常使用時，上下文最好控制在 300K tokens 左右以內；模型窗口更小時，以它的上限為準。",
      "thinkExample": "翻譯一句普通郵件，可以直接答；核對幾條互相牽連的規則，可以打開思考。先用中檔，看看漏項有沒有減少，再決定要不要繼續提高。",
      "fastQuestion": "為什麼不直接選最強的模型？",
      "fastCost": "如果每天要翻譯幾百段文字、處理幾百條記錄，每次多等一點、多花一點，累積起來就是時間和預算。選型時，把答案質量、等待時間和使用費用一起看。",
      "fastExampleTitle": "例如：翻譯一個網頁",
      "fastExample": "假設一次網頁翻譯中，旗艦開啓較高思考強度，花了幾分鐘；輕量模型幾秒就給出譯文，兩份譯文的質量卻沒有明顯差別。這時，用輕量模型就能更快、更省錢地完成工作。",
      "open4a": "調參 / 微調",
      "open4b": "用公司的標準問答、文書範例繼續訓練，讓它更熟悉業務術語、固定格式和回答風格。",
      "open4c": "通過提示詞和設置調整回答；部分服務也提供微調功能。",
      "deskImageAlt": "兩張同樣大小的桌面：左邊攤滿文件，關鍵句被其他紙張遮住；右邊保留問題、聊天記錄和相關資料，關鍵句清楚地露出來。",
      "deskWholeTitle": "材料都放得下",
      "deskWholeText": "紙張層層疊着，關鍵一句也可能被埋住。",
      "deskSelectedTitle": "把這次要用的擺出來",
      "deskSelectedText": "問題和相關證據放在一起，更容易找到重點。",
      "compareTitle": "同一道題，試試兩個模型",
      "compareIntro": "先翻譯郵件，再找出題目裏的坑，最後破解密碼。問題逐漸變難，答案仍然一眼就能核對。",
      "compareSetup": "選一個輕量模型和一個旗艦模型，例如 Qwen3.8-27B 與 Qwen3.8-Max。每題開新對話，發送相同內容，保持相同思考模式，不開啓聯網或代碼工具。",
      "compareInput": "發給兩個模型的同一道題",
      "compareCopy": "複製題目",
      "compareCopied": "已複製",
      "compareCopySuccess": "已複製，可以粘貼到模型對話中。",
      "compareCopyFallback": "請選中下方題目，手動複製。",
      "compareReference": "展開答案，現場核對",
      "compareConclusion": "兩邊都答對，就比較速度和費用；難題出現差距時，再看旗艦多花的時間是否值得。",
      "nav4": "長報告與一頁原文",
      "nav5": "下次工作時，先這樣選",
      "s4": "4. 做個對比：長報告與一頁原文",
      "s4Intro": "開兩個對話，用同一個模型。一個上傳長報告，一個只上傳相關的一頁。兩邊問同樣的問題，再追問一次，最後對照答案。",
      "longSetup": "A、B 兩個新對話選同一個模型，思考模式保持一致。分別上傳下面的 PDF，等上傳完成後再提問。",
      "rawLanguage": "題目與參考答案 · 中文原稿",
      "rawInputLanguage": "演示輸入 · 中文原稿",
      "copyQuestion": "複製問題",
      "groundHead1": "核對點",
      "groundHead2": "正確內容",
      "groundHead3": "原文頁",
      "s5": "5. 下次工作時，先這樣選",
      "chooseHead1": "遇到的情況",
      "chooseHead2": "先做什麼",
      "choose1Situation": "改文字、做簡單整理",
      "choose1Action": "先用快速或默認模型。",
      "choose2Situation": "問題複雜、需要比較多條條件",
      "choose2Action": "先補全條件，再比較旗艦或思考模式是否減少漏項與返工。",
      "choose3Situation": "材料是截圖、掃描件或聲音",
      "choose3Action": "選支持這種輸入的模型。",
      "choose4Situation": "文檔很長、聊天已經很亂",
      "choose4Action": "長文先找相關章節、保留附註和例外；舊對話整理好重點，再開新對話。",
      "choose5Situation": "核對金額、轉賬或作最終審批",
      "choose5Action": "金額核對用表格或計算工具；轉賬與最終審批由人確認。",
      "closingLabel": "今天帶走",
      "closing": "簡單任務看效率，複雜任務看增益，長文任務看證據。",
      "downloadDemo": "下載材料 + 問題包",
      "downloadLanguage": "包含長報告 PDF、單頁 PDF、兩輪提問和參考答案。解壓後照着“怎麼測”操作即可。",
      "longStory": "材料來自 NASA《哥倫比亞事故調查報告》。事故後，NASA 推演過：如果更早發現損傷，宇航員能否等待救援，或者修補後返回？我們就用這段真實材料，看看模型會不會找錯數字、把假設説成事實。",
      "longStep1": "第一步：各上傳一份 PDF",
      "longFileTitle": "A · 上傳長報告",
      "longFileSize": "200 頁 · 149.43 MB",
      "longFileHint": "把前 200 頁整份傳進去，讓模型自己找。",
      "singleFileTitle": "B · 只上傳相關的一頁",
      "singleFileSize": "1 頁 · 0.72 MB",
      "singleFileHint": "只傳原報告第 173 頁，兩輪答案都在這裏。",
      "downloadLongPdf": "下載長報告 PDF",
      "downloadSinglePdf": "下載單頁 PDF",
      "longCropNote": "原報告共 248 頁。演示版去掉末尾 48 頁，保留前 200 頁，文件低於 150 MB。本次問題不涉及刪去的內容，保留頁的正文、圖表和頁碼不變。",
      "longStep2": "第二步：先問，還能在軌待多久？",
      "longFirstHint": "把下面這段原樣發給 A 和 B，等兩邊都回答。",
      "longStep3": "第三步：追問，修補就一定能回來嗎？",
      "longFollowHint": "直接在剛才的兩個對話裏繼續發下面這段，不用重新上傳 PDF。",
      "longFirstAnswer": "展開第 1 輪答案 · 3 項",
      "longFollowAnswer": "展開第 2 輪答案 · 3 項",
      "sourcePageLabel": "原報告第",
      "longStep4": "第四步：對答案，看差別",
      "longScore": "展開每輪下方的參考答案，答對一項記 1 分，兩輪共 6 分。第一輪看數字有沒有串，第二輪看有沒有把假設當事實、把高風險説成有保證。意思正確即可，不要求措辭一樣。",
      "longResult": "先看兩邊各答對幾項，再看花了多久。兩邊都答對，就記錄這次沒有正確率差距；單頁是否更快，也值得比較。"
    },
    "en": {
      "eyebrow": "Week 5 · Models, context & long documents",
      "title": "Choose the model<br>Bring the material",
      "lead": "Translating an email, comparing rules and reading a long report call for different models and materials. Start with these everyday tasks, choose a model, supply what it needs and check the result.",
      "goal": "This week’s goal",
      "goalText": "Recognize the main model types and when a flagship is worth using, then use a real long report to see what changes when you select relevant material.",
      "duration": "15 minutes · Concepts and experiments",
      "nav1": "Meet the model types",
      "nav2": "What reasoning effort changes",
      "nav3": "Why fitting is not enough",
      "s1": "1. Meet the model types",
      "s1Intro": "Start with four questions: how you use it, what it can read, how difficult a task it can handle and whether it can spend more time reasoning. Here is what they mean at work.",
      "modelTitle": "Names you may recognize",
      "modelDate": "Common providers and model examples · 2026-09-17. Get to know the families, then choose a specific model when you use them.",
      "vendorHead": "Vendor",
      "familyHead": "Product / family",
      "modelHead": "Model examples",
      "openaiModels": "GPT-6 Astra, GPT-5.6 series",
      "anthropicModels": "Sonnet 5, Opus 5, Fable 5.1",
      "googleModels": "3.8 Flash, 3.1 Pro (preview)",
      "alibaba": "Alibaba",
      "qwen": "Qwen",
      "productNote": "Grok, used in Week 4, is one of these families. A chat product is the interface; the model handles understanding and generating content.",
      "s2": "2. Reasoning effort: how much work to spend on this answer",
      "s2Intro": "Some models offer low, medium and high reasoning effort. Higher effort lets the model spend more computation breaking down the problem and checking conditions before answering.",
      "paramHead1": "What you see",
      "paramHead2": "What it means",
      "paramHead3": "Why it matters",
      "param1Name": "Parameters · 27B / 70B",
      "param1Meaning": "Think of a model as a machine with many tiny adjustable knobs. Training tunes them using lots of examples; the parameter count is the number of knobs. 27B means about 27 billion.",
      "param1Effect": "More knobs allow more adjustments and combinations, and generally require more memory and computation to run.",
      "param2Name": "Context window · 128K / 1M tokens",
      "param2Meaning": "How much information can fit into the current context.",
      "param2Effect": "Sets how much material and conversation history can fit at once.",
      "param3Name": "Maximum output length",
      "param3Meaning": "How much the model can write in one response.",
      "param3Effect": "A long report may need several responses.",
      "param4Name": "Reasoning effort",
      "param4Meaning": "How much computation to spend on a complex problem.",
      "param4Effect": "Allows more checking on complex tasks and can increase waiting time.",
      "param5Name": "Temperature · Randomness",
      "param5Meaning": "Affects variation when generating an answer.",
      "param5Effect": "Try different settings for rewriting or creative tasks; start with the default for everyday use.",
      "paramNote": "Parameter count comes with your choice of model; reasoning effort and output length are settings you can adjust during use.",
      "s3": "3. Context is like your working desk",
      "s3Intro": "In Week 2 we met tokens: units used to process information. The context window is how much information can fit at a time.",
      "deskLabel": "The same desk, two ways to arrange the material",
      "desk1": "Card · Current question",
      "desk1Note": "What to do now",
      "desk2": "Notes · Chat history",
      "desk2Note": "What was said before",
      "desk3": "Pages · Provided material",
      "desk3Note": "Files, images and notes",
      "deskQuote": "A bigger desk holds more pages. It does not mean every page will be used equally well.",
      "contextWhy": "When answering, a model selects information relevant to the question and connects it. As the desk fills up, it becomes harder to find the key facts, separate similar details and keep track of conditions.",
      "minutes": "min",
      "openTitle": "Open and closed models: host your own or use a service",
      "openIntro": "Open models can be downloaded, hosted and adapted by you or your company. Closed models are provided as a service through a website or API.",
      "openH1": "What to compare",
      "openH2": "Open models",
      "openH3": "Closed models",
      "open1a": "How you use it",
      "open1b": "Download the model and host or adapt it for your needs.",
      "open1c": "Open a chat product or connect to the provider’s API.",
      "open2a": "Running and maintaining it",
      "open2b": "Provide the hardware and maintenance, or use a hosting service.",
      "open2c": "The provider runs and updates it; users pay by subscription or usage.",
      "open3a": "Typical uses",
      "open3b": "Internal knowledge bases, specialised business tools and model customisation.",
      "open3c": "Everyday writing, translation, analysis and adding AI features quickly.",
      "openNote": "A company with a technical team can use an open model to process internal material on its own servers. For daily emails and meeting notes, a ready-to-use chat service is convenient.",
      "modalityTitle": "Text and multimodal models: what material do you have?",
      "textPath": "Text → Tokens → Model processing → Text answer",
      "visionPath": "Image → Visual encoder extracts features → Process alongside the question → Answer",
      "modalityBody": "Text models work with words. Multimodal models can also work with inputs such as images or sound. A common approach to vision divides an image into patches, uses a visual encoder to extract text, shapes and positions, then processes those features with your question.",
      "modalityExample": "For example, text extracted from a chart may contain only dates and numbers. A vision model can also use the curves, colours and crossing points to understand which change you mean.",
      "modalityNote": "For an email, text input is enough. For scans and charts, choose image support. For recordings, choose audio support.",
      "fastTitle": "Lightweight and flagship models",
      "fastBody": "An expert can solve an elementary-school problem, but the extra time and cost may buy little. Fast models are often enough for translating emails, rewriting sentences and extracting clear fields. Try a flagship when the task involves several rules, exceptions and trade-offs.",
      "fastNote": "Names such as Flash, Lite and mini usually emphasise speed and cost. Flagship models often spend more computation on complex tasks, helping reduce omissions and rework.",
      "thinkFlow": "Read the question → Break it down → Check conditions and candidate answers → Respond",
      "thinkBody": "Those intermediate steps also generate tokens, which take time and computing resources. Higher effort leaves the model’s parameters and learned knowledge unchanged; it does more work for this answer, whose final wording can still be brief.",
      "thinkControls": "What the controls change",
      "thinkH1": "Control",
      "thinkH2": "What it controls",
      "think1a": "Reasoning mode · On / off",
      "think1b": "Choose whether to reason through intermediate steps before answering.",
      "think2a": "Reasoning effort · Low / medium / high",
      "think2b": "Set how much effort the model should spend on the task.",
      "think3a": "Reasoning budget",
      "think3b": "Cap the intermediate reasoning to manage waiting time and cost.",
      "paramTitle": "A few other settings to recognise",
      "context1Title": "Similar information can get mixed up",
      "context1": "A report contains measured dimensions, estimates and assumptions. The model may find a number but attach it to the wrong event.",
      "context2Title": "Conditions far apart are easier to miss",
      "context2": "The general rule is near the beginning and the exception is much later. Answering requires combining both; dozens of pages between them make it easier to use only one.",
      "context3Title": "Old conversation can pull the answer off course",
      "context3": "After many turns and several changes of plan, old and new instructions remain in the same history. The next answer may reuse a requirement you already changed.",
      "contextGuideTitle": "How much material to start with",
      "contextGuideBody": "For everyday use, aim to keep context within roughly 300K tokens, or within the model’s limit if its window is smaller.",
      "thinkExample": "A straightforward email translation can use a direct answer. Turn reasoning on for several connected rules. Start with medium effort and see whether it reduces omissions before increasing it.",
      "fastQuestion": "Why not just choose the strongest model?",
      "fastCost": "If you translate hundreds of passages or process hundreds of records each day, small increases in waiting time and cost add up. Compare answer quality, waiting time and running cost together.",
      "fastExampleTitle": "For example: translating a web page",
      "fastExample": "Imagine a web-page translation where a flagship at high reasoning effort takes several minutes, while a lightweight model delivers in seconds and the translations are similar in quality. The lightweight model gets that job done faster and at lower cost.",
      "open4a": "Tuning / fine-tuning",
      "open4b": "Train further on company Q&A and document examples to adapt its terminology, formats and response style.",
      "open4c": "Adjust responses through prompts and settings; some services also offer fine-tuning.",
      "deskImageAlt": "Two desks of the same size: the left is crowded with documents that obscure a key line; the right keeps the question, chat history and relevant sources, leaving the key line visible.",
      "deskWholeTitle": "All the material fits",
      "deskWholeText": "Overlapping pages can still bury the key line.",
      "deskSelectedTitle": "Lay out what this task needs",
      "deskSelectedText": "The question and relevant evidence are together and easier to find.",
      "compareTitle": "One question, two models",
      "compareIntro": "Start with a translation, then spot a trap and crack a code. The questions get harder while the answers stay easy to check.",
      "compareSetup": "Choose a lightweight model and a flagship, such as Qwen3.8-27B and Qwen3.8-Max. Start a fresh chat for each question, send identical prompts and use the same reasoning mode, without browsing or code tools.",
      "compareInput": "Send the same question to both models",
      "compareCopy": "Copy question",
      "compareCopied": "Copied",
      "compareCopySuccess": "Copied. Paste it into the model chat.",
      "compareCopyFallback": "Select the question below and copy it manually.",
      "compareReference": "Reveal the answer and check it",
      "compareConclusion": "If both are correct, compare speed and cost. When harder questions reveal a gap, see whether the flagship is worth the extra time.",
      "nav4": "A long report vs one page",
      "nav5": "Choose for your next task",
      "s4": "4. Try it: a long report vs one page",
      "s4Intro": "Open two chats with the same model. Upload the long report in one and just the relevant page in the other. Ask the same question and one follow-up, then compare the answers.",
      "longSetup": "Choose the same model and reasoning mode in two fresh chats, A and B. Upload the matching PDF below and wait for the upload to finish before asking.",
      "rawLanguage": "Questions and answers · Simplified Chinese originals",
      "rawInputLanguage": "Demo input · Simplified Chinese original",
      "copyQuestion": "Copy prompt",
      "groundHead1": "Check",
      "groundHead2": "Expected content",
      "groundHead3": "Source page",
      "s5": "5. Choose for your next task",
      "chooseHead1": "Situation",
      "chooseHead2": "What to try first",
      "choose1Situation": "Rewrite text or organize simple material",
      "choose1Action": "Start with a fast or default model.",
      "choose2Situation": "A complex question with several conditions",
      "choose2Action": "Provide all the conditions, then see whether a flagship or reasoning mode reduces omissions and rework.",
      "choose3Situation": "Screenshots, scans or audio",
      "choose3Action": "Choose a model that supports that input.",
      "choose4Situation": "Long documents or a messy chat history",
      "choose4Action": "Find the relevant sections with their notes and exceptions. For a messy chat, collect the key points and start a new conversation.",
      "choose5Situation": "Check amounts, transfer funds or give final approval",
      "choose5Action": "Use spreadsheets or calculation tools to check amounts. People confirm transfers and final approvals.",
      "closingLabel": "Take this with you",
      "closing": "For simple tasks, compare efficiency. For complex tasks, compare improvement. For long documents, check the evidence.",
      "downloadDemo": "Download materials + prompts",
      "downloadLanguage": "Includes the long PDF, single-page PDF, two prompts and reference answers. Unzip the pack and follow the short guide.",
      "longStory": "The material comes from NASA’s Columbia Accident Investigation Board Report. After the accident, NASA studied whether earlier discovery of the damage could have allowed a rescue or repair. Check whether the model finds the right numbers and keeps assumptions separate from facts.",
      "longStep1": "Step 1: upload one PDF in each chat",
      "longFileTitle": "A · Upload the long report",
      "longFileSize": "200 pages · 149.43 MB",
      "longFileHint": "Upload all 200 pages and let the model find the relevant details.",
      "singleFileTitle": "B · Upload only the relevant page",
      "singleFileSize": "1 page · 0.72 MB",
      "singleFileHint": "Upload original page 173. It contains the answers to both rounds.",
      "downloadLongPdf": "Download the long PDF",
      "downloadSinglePdf": "Download the single page",
      "longCropNote": "The original report has 248 pages. The demo removes the last 48 pages and keeps pages 1–200, bringing the file below 150 MB. Neither question needs the removed pages. Text, figures and page numbers on retained pages are unchanged.",
      "longStep2": "Step 2: ask how long the crew could stay in orbit",
      "longFirstHint": "Send the exact prompt below to both A and B, then wait for both answers.",
      "longStep3": "Step 3: ask whether a repair would guarantee a safe return",
      "longFollowHint": "Send this follow-up in the same two chats. There is no need to upload the PDFs again.",
      "longFirstAnswer": "Show round 1 answers · 3 checks",
      "longFollowAnswer": "Show round 2 answers · 3 checks",
      "sourcePageLabel": "Original report page",
      "longStep4": "Step 4: check the answers and compare",
      "longScore": "Open the reference answers below each round. Give one point per correct item, for six points in total. Round 1 checks numbers; round 2 checks assumptions, risk and certainty. Equivalent wording is fine.",
      "longResult": "Compare the number of correct items first, then the time taken. If both are correct, record that this trial showed no accuracy difference. You can still compare their speed."
    }
  },
  "comparison": {
    "zh-CN": [
      {
        "id": "translation",
        "title": "01 · 翻译邮件",
        "prompt": "请将下面这封邮件翻译成自然、简洁的英文。保留时间、时区和“草稿”的含义，不自行添加审批承诺：\n\n请在周五下午 3 点（香港时间）前把修订后的报告草稿发给我。我会先核对数字，再转给团队讨论。谢谢。",
        "answer": "意思完整、表达自然，就算过关。",
        "explanation": "参考译法：Please send me the revised draft report by 3 p.m. Hong Kong time on Friday. I’ll check the figures first, then share it with the team for discussion. Thank you.",
        "note": "这题先看两份译文是否都能直接使用，再比较速度和费用。",
        "columns": [],
        "checks": [
          "周五下午 3 点，香港时间。",
          "是修订后的草稿；先核对数字，再交给团队讨论。",
          "没有把“讨论”变成“批准”，不必逐字一致。"
        ],
        "rows": []
      },
      {
        "id": "cake",
        "title": "02 · 谁偷吃了蛋糕",
        "prompt": "最后一块蛋糕被吃掉了。甲、乙、丙、丁中，恰好有一人偷吃。四人各说了一句话：\n\n甲：“是乙吃的。”\n乙：“是丁吃的。”\n丙：“不是我吃的。”\n丁：“乙说的是假话。”\n\n已知这四句话中，恰好两句是真话、两句是假话。\n\n请找出唯一的偷吃者，回答名字，并用一句话说明理由。",
        "answer": "不能唯一确定：甲或丁。",
        "explanation": "题目要求“唯一”，但给出的条件不够。甲吃了、丁吃了，都能让两句话为真；强行选一个名字，就漏掉了另一种可能。",
        "note": "这题看的是：模型会不会因为你说了“唯一”，就顺着题目编出一个唯一答案。",
        "columns": [
          "假设谁吃了",
          "谁说的是真话",
          "真话数量"
        ],
        "checks": [],
        "rows": [
          [
            "甲",
            "丙、丁",
            "2 ✓"
          ],
          [
            "乙",
            "甲、丙、丁",
            "3"
          ],
          [
            "丙",
            "丁",
            "1"
          ],
          [
            "丁",
            "乙、丙",
            "2 ✓"
          ]
        ]
      },
      {
        "id": "password",
        "title": "03 · 破解六位密码",
        "prompt": "保险箱的密码由 6 个互不重复的数字组成，数字范围是 0–9，允许以 0 开头。\n\n下面每条线索的数量都恰好成立：\n“位置正确”表示数字和位置都对；\n“位置错误”表示数字在密码中，但位置不对；\n其余数字都不在密码中，两类计数不重复。\n\n猜测      位置正确  位置错误\n214605       1         3\n754198       1         3\n023918       1         3\n634758       0         4\n604137       1         3\n\n请找出密码。只输出六位密码，再用一句话说明核对结果。不要联网或使用代码工具。",
        "answer": "583104",
        "explanation": "五条线索全部满足，而且只有这一组密码符合。对照下面的数字，就能逐行检查。",
        "note": "这题看的是：能不能同时满足五条线索。先看六位数是否正确，再看解释有没有漏掉某一行。",
        "columns": [
          "猜测",
          "数字和位置都对",
          "数字对、位置错"
        ],
        "checks": [],
        "rows": [
          [
            "214605",
            "0 → 1 个",
            "1、4、5 → 3 个"
          ],
          [
            "754198",
            "1 → 1 个",
            "5、4、8 → 3 个"
          ],
          [
            "023918",
            "3 → 1 个",
            "0、1、8 → 3 个"
          ],
          [
            "634758",
            "无 → 0 个",
            "3、4、5、8 → 4 个"
          ],
          [
            "604137",
            "1 → 1 个",
            "0、4、3 → 3 个"
          ]
        ]
      }
    ],
    "zh-TW": [
      {
        "id": "translation",
        "title": "01 · 翻譯郵件",
        "prompt": "請將下面這封郵件翻譯成自然、簡潔的英文。保留時間、時區和“草稿”的含義，不自行添加審批承諾：\n\n請在週五下午 3 點（香港時間）前把修訂後的報告草稿發給我。我會先核對數字，再轉給團隊討論。謝謝。",
        "answer": "意思完整、表達自然，就算過關。",
        "explanation": "參考譯法：Please send me the revised draft report by 3 p.m. Hong Kong time on Friday. I’ll check the figures first, then share it with the team for discussion. Thank you.",
        "note": "這題先看兩份譯文是否都能直接使用，再比較速度和費用。",
        "columns": [],
        "checks": [
          "週五下午 3 點，香港時間。",
          "是修訂後的草稿；先核對數字，再交給團隊討論。",
          "沒有把“討論”變成“批准”，不必逐字一致。"
        ],
        "rows": []
      },
      {
        "id": "cake",
        "title": "02 · 誰偷吃了蛋糕",
        "prompt": "最後一塊蛋糕被吃掉了。甲、乙、丙、丁中，恰好有一人偷吃。四人各説了一句話：\n\n甲：“是乙吃的。”\n乙：“是丁吃的。”\n丙：“不是我吃的。”\n丁：“乙説的是假話。”\n\n已知這四句話中，恰好兩句是真話、兩句是假話。\n\n請找出唯一的偷吃者，回答名字，並用一句話説明理由。",
        "answer": "不能唯一確定：甲或丁。",
        "explanation": "題目要求“唯一”，但給出的條件不夠。甲吃了、丁吃了，都能讓兩句話為真；強行選一個名字，就漏掉了另一種可能。",
        "note": "這題看的是：模型會不會因為你説了“唯一”，就順着題目編出一個唯一答案。",
        "columns": [
          "假設誰吃了",
          "誰説的是真話",
          "真話數量"
        ],
        "checks": [],
        "rows": [
          [
            "甲",
            "丙、丁",
            "2 ✓"
          ],
          [
            "乙",
            "甲、丙、丁",
            "3"
          ],
          [
            "丙",
            "丁",
            "1"
          ],
          [
            "丁",
            "乙、丙",
            "2 ✓"
          ]
        ]
      },
      {
        "id": "password",
        "title": "03 · 破解六位密碼",
        "prompt": "保險箱的密碼由 6 個互不重複的數字組成，數字範圍是 0–9，允許以 0 開頭。\n\n下面每條線索的數量都恰好成立：\n“位置正確”表示數字和位置都對；\n“位置錯誤”表示數字在密碼中，但位置不對；\n其餘數字都不在密碼中，兩類計數不重複。\n\n猜測      位置正確  位置錯誤\n214605       1         3\n754198       1         3\n023918       1         3\n634758       0         4\n604137       1         3\n\n請找出密碼。只輸出六位密碼，再用一句話説明核對結果。不要聯網或使用代碼工具。",
        "answer": "583104",
        "explanation": "五條線索全部滿足，而且只有這一組密碼符合。對照下面的數字，就能逐行檢查。",
        "note": "這題看的是：能不能同時滿足五條線索。先看六位數是否正確，再看解釋有沒有漏掉某一行。",
        "columns": [
          "猜測",
          "數字和位置都對",
          "數字對、位置錯"
        ],
        "checks": [],
        "rows": [
          [
            "214605",
            "0 → 1 個",
            "1、4、5 → 3 個"
          ],
          [
            "754198",
            "1 → 1 個",
            "5、4、8 → 3 個"
          ],
          [
            "023918",
            "3 → 1 個",
            "0、1、8 → 3 個"
          ],
          [
            "634758",
            "無 → 0 個",
            "3、4、5、8 → 4 個"
          ],
          [
            "604137",
            "1 → 1 個",
            "0、4、3 → 3 個"
          ]
        ]
      }
    ],
    "en": [
      {
        "id": "translation",
        "title": "01 · Translate an email",
        "prompt": "Translate the following email into natural, concise English. Preserve the deadline, time zone and the fact that this is a draft. Do not add a promise to approve it:\n\n请在周五下午 3 点（香港时间）前把修订后的报告草稿发给我。我会先核对数字，再转给团队讨论。谢谢。",
        "answer": "Complete meaning and natural wording are enough.",
        "explanation": "One possible translation: Please send me the revised draft report by 3 p.m. Hong Kong time on Friday. I’ll check the figures first, then share it with the team for discussion. Thank you.",
        "note": "First check whether both translations are ready to use, then compare time and cost.",
        "columns": [],
        "checks": [
          "Friday, 3 p.m., Hong Kong time.",
          "It is a revised draft; check the figures first, then share with the team.",
          "Discussion has not become approval. The wording need not match exactly."
        ],
        "rows": []
      },
      {
        "id": "cake",
        "title": "02 · Who ate the cake?",
        "prompt": "Someone ate the last slice of cake. Exactly one of A, B, C and D ate it. Each makes one statement:\n\nA: “B ate it.”\nB: “D ate it.”\nC: “I did not eat it.”\nD: “B’s statement is false.”\n\nExactly two of these four statements are true and two are false.\n\nIdentify the single culprit. Give the name and one sentence explaining why.",
        "answer": "No unique answer: A or D.",
        "explanation": "The question demands one culprit, but the clues do not support that. Both A and D make exactly two statements true. Naming just one misses another valid possibility.",
        "note": "Check whether the model invents a unique answer just because the question asks for one.",
        "columns": [
          "Suppose the culprit is",
          "True statements",
          "True count"
        ],
        "checks": [],
        "rows": [
          [
            "A",
            "C, D",
            "2 ✓"
          ],
          [
            "B",
            "A, C, D",
            "3"
          ],
          [
            "C",
            "D",
            "1"
          ],
          [
            "D",
            "B, C",
            "2 ✓"
          ]
        ]
      },
      {
        "id": "password",
        "title": "03 · Crack a six-digit code",
        "prompt": "A safe has a six-digit code made of distinct digits from 0 to 9. A leading zero is allowed.\n\nEvery count below is exact:\n“Right place” means the digit and its position are correct.\n“Wrong place” means the digit is in the code, but at another position.\nAll other guessed digits are absent. The two counts do not overlap.\n\nGuess     Right place  Wrong place\n214605         1            3\n754198         1            3\n023918         1            3\n634758         0            4\n604137         1            3\n\nFind the code. Output the six digits and one sentence confirming your checks. Do not browse or use code tools.",
        "answer": "583104",
        "explanation": "All five clues are satisfied, and this is the only matching code. Check each row using the digits below.",
        "note": "Check whether the model satisfies all five clues. Start with the six digits, then see whether its explanation skips a row.",
        "columns": [
          "Guess",
          "Right digit, right place",
          "Right digit, wrong place"
        ],
        "checks": [],
        "rows": [
          [
            "214605",
            "0 → 1 digit",
            "1, 4, 5 → 3 digits"
          ],
          [
            "754198",
            "1 → 1 digit",
            "5, 4, 8 → 3 digits"
          ],
          [
            "023918",
            "3 → 1 digit",
            "0, 1, 8 → 3 digits"
          ],
          [
            "634758",
            "None → 0 digits",
            "3, 4, 5, 8 → 4 digits"
          ],
          [
            "604137",
            "1 → 1 digit",
            "0, 4, 3 → 3 digits"
          ]
        ]
      }
    ]
  },
  "experiments": {
    "common": "请只依据我上传的报告 PDF 回答，不要联网。用中文简短回答，每项注明原报告页脚的页码。找不到的内容就写“材料未给出”。",
    "evidence_page": 173,
    "rounds": [
      {
        "id": "endurance",
        "title": "第 1 轮 · 还能在轨待多久？",
        "en": "Round 1 · How long could the crew stay in orbit?",
        "question": "报告事后讨论了一个假设：如果更早发现哥伦比亚号的损伤，让宇航员节约消耗、等待救援，还能争取多少时间？\n\n请找出三项信息：\n1. 最先限制留轨时间的耗材是什么？\n2. 调整宇航员的活动和睡眠后，二氧化碳能保持在可接受水平，到第几个飞行日（Flight Day）？\n3. 氧气又要求宇航员在第几个飞行日返回？\n\n按三行回答，保留 Flight Day 的数字，并注明原报告页码。",
        "checks": [
          [
            "最先限制的耗材",
            "氢氧化锂罐，用来吸收二氧化碳。",
            173,
            "limiting consumable was the lithium hydroxide"
          ],
          [
            "二氧化碳",
            "Flight Day 30（第 30 个飞行日）。",
            173,
            "levels until Flight Day 30"
          ],
          [
            "氧气",
            "要求在 Flight Day 31（第 31 个飞行日）返回。",
            173,
            "return on Flight Day 31"
          ]
        ],
        "traditional": "第 1 輪 · 還能在軌待多久？"
      },
      {
        "id": "repair",
        "title": "第 2 轮 · 修补就一定能回来吗？",
        "en": "Round 2 · Would a repair guarantee a safe return?",
        "question": "继续根据这份报告判断，有人这样总结：\n“只要堵住那个 6 英寸的破洞，哥伦比亚号就能安全返回，而且修补比另派航天飞机救援更稳妥。”\n\n这段话成立吗？请逐项纠正：\n1. 这里的“6 英寸”是实际撞击试验的结果，还是修补方案里的假设？\n2. 报告怎样评价修补方案的风险，是否保证安全返回？\n3. 修补和救援，报告认为哪个让宇航员生还的机会更高？\n\n按三行简短回答，并注明原报告页码。",
        "checks": [
          [
            "6 英寸是什么",
            "修补方案假设的破洞大小，不是实际撞击试验的结果。",
            173,
            "assumed 6-inch hole"
          ],
          [
            "修补能否保证安全",
            "不能。报告将修补评为高风险（high risk），无法确认修补能撑过再入。",
            173,
            "NASA rated this option “high risk.”"
          ],
          [
            "哪种机会更高",
            "救援。报告认为救援让宇航员生还的机会明显更高。",
            173,
            "rescue option had a considerably higher chance"
          ]
        ],
        "traditional": "第 2 輪 · 修補就一定能回來嗎？"
      }
    ],
    "files": {
      "long": {
        "filename": "caib-first-200-pages.pdf",
        "pages": 200,
        "bytes": 149429140,
        "original_pages": 248
      },
      "single": {
        "filename": "caib-page-173.pdf",
        "pages": 1,
        "original_page": 173,
        "bytes": 715824
      }
    }
  }
};
